internal/allocator/allocator.go
ipConfusesBuggyFirmwares could potentially do a `len(a)-1` when a would
be nil, leading to -1 --> out of bounds.
=> Fix potential out-of-bounds

arp-speaker/main.go, internal/arp/arp.go
This adds a arp-speaker that will make an LB IP exist on the LAN by
responding to ARP request for that IP. It needs to run on a single node
and will use that node's MAC address as the destination for the service
IP.
No config changes are needed, arp-speaker will consume bgp-speaker
config and only use what it needs.
This PR only *adds* arp-speaker, it has not been hooked up to be
actually used by metallb.
Also: not tested \0/ and there is no periodic routine sending out unsolicated ARP responses.
=> Add arp-speaker

arp-speaker/leadership.go, arp-speaker/main.go, internal/arp/arp.go, internal/arp/leader.go, internal/k8s/k8s.go
Make arp-speaker simpler, implement leaderelection and provide the
framework for sending unsolicitated ARPs on acquiring leadership
~~(actually sending not implemented yet).~~
I needed access to the k8s client, hence the internal/k8s/kus.go change,
the rest is all local to the arp stuff.
All not tested; but this should give me a base to allow some local
testing.
=> Cleanup: arp-speaker

arp-speaker/main.go, internal/k8s/k8s.go, internal/k8s/leader.go
This moves the code into k8s.
*cleanup*
Fixes no issue, but discussued offline.
=> Move leadership code into internal/k8s

arp-speaker/main.go, internal/arp/arp.go
When deleting an LB check if we even have an LB for that name in the
first place; if so, short circuit and don't log anything.
=> arp-speaker: less spammy logs

internal/arp/arp.go, internal/arp/arp_test.go
Initial tests for the ARP announcer read loop.
Fixes # n/a
This works, but I think I should probably rework my ARP package a bit to not depend on an interface handle, since it mostly cares about addresses anyway.
=> internal/arp: initial tests for Announce.Run logic

AUTHORS, controller/controller_test.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/config/config.go, internal/config/config_test.go, manifests/example-config.yaml, website/content/usage.md
A proposed implementation of the "disable auto assign" feature brought up in #4 
**Which issue(s) this PR fixes**:
Fixes #4 
Defaulting the flag to true required some changes in the test configurations. Maybe it would be cleaner to name it `disable-auto-assign` so we can go with the zero bool value if the flag has not been set in the YAML?
=> Add disable auto assign flag

internal/config/config.go, internal/config/config_test.go, speaker/arp_controller.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go
Move proto down to the address pools, also drop the Proto prefix on ProtoBGP, so it is just
BGP, looks nicer.
Fixes #80
=> Make proto a property of the pool

speaker/bgp_controller.go
pool == nil afterwards, we should just return as we do for ARP.
=> bgp-speaker: return when we can't the pool

internal/config/config.go, speaker/arp_controller.go, speaker/bgp_controller.go
Protocol in the config wasn't parsed at all, leading to the default of bgp.
Fix this.
=> Correctly parse things

internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/config/config.go, internal/config/config_test.go, manifests/example-config.yaml
Adds the `arp-network` pool attribute, and teaches MetalLB to not allocate network+broadcast IPs in ARP mode.
**Which issue(s) this PR fixes**
Fixes #110
=> Arp network

internal/k8s/leader.go, internal/k8s/stats.go
Add Gauge to tell what binary has won the leadership election.
Gauge is 1 when leader, 0 when not and initially set to -1 (never leader
or not interested.)
=> leadership monitoring

speaker/main.go
Restart the le.Run() (in 10s) when we crash out of it.
Fixes #131
=> leadership: restart loop when we crash out

internal/k8s/leader.go, speaker/main.go
Each replica of speaker must have a distinct identity for leader election, because that's the key they use to decide who is master. We were accidentally setting the identity to the same thing in all instances of speaker, so they all "became" leader simultaneously.
=> Give each instance of speaker a unique identity for leader election.

glide.lock, glide.yaml, vendor/github.com/mikioh/ipaddr/.gitignore, vendor/github.com/mikioh/ipaddr/.travis.yml, vendor/github.com/mikioh/ipaddr/LICENSE, vendor/github.com/mikioh/ipaddr/README.md, vendor/github.com/mikioh/ipaddr/appveyor.yml, vendor/github.com/mikioh/ipaddr/benchmark_test.go, vendor/github.com/mikioh/ipaddr/cursor.go, vendor/github.com/mikioh/ipaddr/cursor_test.go, vendor/github.com/mikioh/ipaddr/doc.go, vendor/github.com/mikioh/ipaddr/example_test.go, vendor/github.com/mikioh/ipaddr/heap_test.go, vendor/github.com/mikioh/ipaddr/helper.go, vendor/github.com/mikioh/ipaddr/helper_go1_8.go, vendor/github.com/mikioh/ipaddr/helper_go1_9.go, vendor/github.com/mikioh/ipaddr/parse.go, vendor/github.com/mikioh/ipaddr/parse_test.go, vendor/github.com/mikioh/ipaddr/position.go, vendor/github.com/mikioh/ipaddr/position_test.go, vendor/github.com/mikioh/ipaddr/prefix.go, vendor/github.com/mikioh/ipaddr/prefix_test.go, vendor/github.com/mikioh/ipaddr/sort.go, vendor/github.com/mikioh/ipaddr/sort_go1_7.go, vendor/github.com/mikioh/ipaddr/sort_go1_8.go
Vendors in an IP address prefix and address walking package to replace the existing IPv4 only implementations.
Fixes # n/a
I figure this will be easier than making some of the current allocator functions also deal with IPv6.
=> vendor: add github.com/mikioh/ipaddr

internal/allocator/allocator.go, internal/allocator/allocator_test.go
Makes use of `ipaddr`'s address traversal functions, which can also deal with IPv6 addresses.  IPv4 addresses are still assumed in this PR because IPv6 addresses will need to be threaded through the code later.
Fixes # n/a
n/a
=> internal/allocator: replace address traversal with ipaddr package

internal/arp/arp.go, speaker/bgp_controller_test.go, speaker/main.go
First pass at threading a bit of IPv6 goodness through the speaker.
Updates #7.
I tried to make things a bit more extensible and general, and got a head start on plumbing a bit of IPv6 addressing through.  It probably needs more work though.
=> speaker: allow speaker to have an IPv6 address

internal/ndp/leader.go, internal/ndp/ndp.go, speaker/bgp_controller_test.go, speaker/main.go, speaker/ndp_controller.go
Hooks up the NDP speaker to the `speaker` binary.
Updates #83, but may be very close to fixing it too.
Will be rebased after #154 and #155 are merged.  I split them up for easier review.
This _might_ actually work but I can't tell at the moment because I haven't found a network addon that can do both IPv6 and runs on ARM.  But I could see TCP traffic (HTTP) being pulled at my speaker's advertised IPv6 address, so assuming Kubernetes can do its thing, I think I've about got it!
=> speaker: plumb in NDP speaker

website/content/configuration/_index.md, website/content/tutorial/minikube.md
Update documentation to use [rfc5398](https://tools.ietf.org/html/rfc5398) documentation ranges for ASNs.
**Which issue(s) this PR fixes** 
Fixes #158 
Thanks @danderson for being so responsive
=> Issues/158 - documentation asn ranges

internal/config/config.go, internal/config/config_test.go
As foretold in #198.
Fixes #198
=> internal/config: remove deprecated field names.

Makefile
Original Makefile was using `echo` to construct Makefile.images-target. echo is not very portable especially on MacOS. `-n` does not work well. Switch to use `printf` which is POSIX standard.
Closes: #211
=> Switch from echo to printf for portability

manifests/metallb.yaml
Controller needs `patch` permission for events. Adding it to deployment yaml.
Closes #213
=> Adding patch permission to controller

internal/layer2/announcer.go, internal/layer2/arp.go, internal/layer2/leader.go
Every 10s, the layer2 controller scans interfaces, and runs an ARP
responder for each interface with a globally routable IPv4 address
(note this includes RFC1918).
=> Listen for ARP requests on all interfaces. #165

.circleci/config.yml, .circleci/config.yml.tmpl, Makefile, helm-chart/.helmignore, helm-chart/Chart.yaml, helm-chart/README.md, helm-chart/templates/NOTES.txt, helm-chart/templates/_helpers.tpl, helm-chart/templates/config.yaml, helm-chart/templates/controller.yaml, helm-chart/templates/rbac.yaml, helm-chart/templates/service-accounts.yaml, helm-chart/templates/speaker.yaml, helm-chart/values.yaml, manifests/metallb.yaml, manifests/namespace.yaml, website/content/community/release-process.md
Having the helm chart here means we can prepare changes to the chart in lockstep with other changes to MetalLB. It does add a release step, in that we have to go back and resync the official chart.
=> Reimport a copy of the Helm chart.

helm-chart/templates/controller.yaml, helm-chart/templates/speaker.yaml, helm-chart/values.yaml
This allows setting the `nodeSelector`, `tolerations` and `affinity` for both the speaker
and controller. This is useful for limiting the nodes that the speaker daemons pods are run on.
Default values are also set in `values.yaml` so that the yaml is well-formed.
Closes #222
=>  Helm: Add support for nodeSelector/tolerations/affinity

e2etest/e2e_setup_test.go, internal/bgp/messages.go
The spec requires route originators to specify their ASN
in an AS_SEQUENCE path segment (which makes sense if you
think about it... AS_SET encodes a path that goes "via one
of these ASNs", which is impossible fo the *originating* ASN).
Fixes #225.
=> Correctly use AS_SEQUENCE in path attributes.

internal/layer2/announcer.go, internal/layer2/arp.go, internal/layer2/arp_test.go
There is a valid use case for having interfaces that are "services-only",
i.e. are marked up, but don't have global unicast addresses of their own.
Such addresses can still participate in layer2 mode advertisements, and
it can significantly save on the number of IPs in use on the network.
This change therefore listens on all interfaces that are up and support
the features required by ARP/NDP (e.g. broadcast, multicast, existence
of a link-local address...).
Fixes #226
=> Listen on all structurally valid interfaces, regardless of addresses.

helm-chart/templates/speaker.yaml, internal/layer2/announcer.go, manifests/metallb.yaml, speaker/bgp_controller_test.go, speaker/main.go
There's no longer any need to pass in the node IP, or look up the
relevant interface.
=> Clean up old code related to layer2 interface selection. #226

controller/Dockerfile, controller/main.go, speaker/Dockerfile, speaker/main.go
We are fortunate, in that we only register flags in main.go, so we can
just overwrite the base commandline flag set with a new one, which
effectively hides all flags that weren't defined in main(). Just before
doing that, we set --logtostderr=true for glog, so that it doesn't try
to do file I/O other than writing to os.Stderr.
This is step one of trying to remove glog from MetalLB.
=> Hide glog's flags from the commandline. #189

internal/k8s/k8s.go
Oops, this broke IP allocation in the controller. Oh well.
=> Fire the "synced" callback if it's registered.

internal/bgp/bgp.go, internal/bgp/bgp_test.go, internal/config/config.go, manifests/example-config.yaml, speaker/bgp_controller.go, speaker/bgp_controller_test.go, website/content/configuration/_index.md
The default net.Conn object is replaced by  low level
syscalls that create the FD's set the sockopts directly,
as TCP MD5  sockopts have to be set before the connection
is made.
This PR attempts to provide a new feature TCP MD5  BGP auth, 
Fixes # #215 
This is of course a my first interaction with GOLANG,  not perfect, but done is better than missing. 
There is code and inspiration from gopgp, expect some similarities.
=> This PR adds support for TCP MD5 auth in metallb.

website/content/installation/_index.md
Code review latency seems to be >1w right now, so I need to set
appropriate expectations for MetalLB's users.
=> Document that the Helm chart is currently outdated.

internal/bgp/bgp.go
=> Check for closed or aborted BGP sessions before sending the initial BGP update

internal/k8s/k8s.go
Thank you for this wonderful software!
**What this PR does / why we need it**: This change restores the logging of error messages that were removed when these logs were moved from glog to go-kit in https://github.com/google/metallb/commit/462b4758763d68f1a7a66998026a24847d9ed42a. This should help other users track down issues with config moving from 0.5.x to 0.6.x
It looks like there is a request for better error config parsing messages overall in https://github.com/google/metallb/issues/201. This change will be necessary for those improvements but I feel that surfacing the YAML parsing errors are helpful enough to do this now.
=> Log error messages encountered during ConfigMap parsing

website/content/tutorial/layer2.md
Fixes small nit on docs when applying layer2 config.
=> Fix layer2 config name to match repo

controller/service.go
Remove a check for ipv4 to allow also ipv6 addresses.
This PR removes a check that loadBalancerIP is ipv4.
It is needed to allow also ipv6 addresses. 
**Which issue(s) this PR fixes**
Fixes #301 
This is a very tiny fix. It is necessary for using the controller in an ipv6 k8s cluster but it is also a test of the PR procedure, especially CLA which should work now...
=> Fix for issue #301

internal/bgp/bgp.go
This PR uses an ipv4 address, if it is exists, as routerID in an ipv6-only cluster. The ipv4 address is taken from the same interface as for the BGP peering (don't know if that is really necessary). It also removes usage of 0.0.0.0/0 as local address and use [::]:0 instead (this is ipv4 compatibe).
This PR makes peering possible with ipv6 peers without special configuration. It is a step towards ipv6 support for bgp #7.
Address announcement still does not work;
```
{"caller":"main.go:214","error":"cannot advertise non-v4 prefix \"\u003cnil\u003e\"","ip":"1000::","msg":"failed to announce service","op":"setBalancer","pool":"default","protocol":"bgp","service":"default/mconnect","ts":"2018-09-24T07:19:49.784240262Z"}
```
so more work is needed to …
=> Ipv6; Use ipv4 address as routerId also for ipv6 clusters

speaker/bgp_controller.go
Fixed the "too many colons" error when ipv6 addresses are used for peers.
This is another attempt at PR 239 but fixed as suggested by @danderson 
This PR is needed to get BGP peering working with ipv6 peers.
**Which issue(s) this PR fixes**
A step on the way for  #7 
See [pr-239](https://github.com/google/metallb/pull/239)
=> Undestrand ipv6 peer addresses

helm-chart/templates/controller.yaml, helm-chart/templates/speaker.yaml
This PR sets a nodeSelector for limiting the deployment via helm to linux OS nodes only.
Fixes #324
=> Add OS nodeSelector for linux to allow for hybrid cluster.

internal/layer2/announcer.go
This PR disables listening on interfaces which have master
**Which issue(s) this PR fixes**:
Fixes #349
=> Layer 2: do not listen slave interfaces

website/content/configuration/romana.md
Romana's documentation link was broken and was updated with the right address.
=> fix broken link

helm-chart/templates/speaker.yaml, manifests/metallb.yaml
Otherwise services for pods that run on master nodes would not be announced
Related: https://github.com/google/metallb/issues/371
It adds the `node-role.kubernetes.io/master:NoSchedule` toleration to the `speaker` `DaemonSet` so that `speaker` was also deployed on master nods
Fixes #371
=> Added `node-role.kubernetes.io/master:NoSchedule` to the `ds/speaker`

internal/layer2/announcer.go, internal/layer2/announcer_test.go
Multiple services with the same IP address should be added to the list of the announced services no matter how many times the IP address is used.
This PR is fixing the issue when layer 2 ARP announcer function SetBalancer is called multiple times for several services sharing the same IP address. After adding the first service the following calls of SetBalancer with the same IP address increasing the IP address usage counter but do not add services to the list of the announced ones. This prevents DeleteBalancer from releasing the IP address when the services are not announced anymore. 
Fixes #402
=> Add service to the announced ones

manifests/example-config.yaml
Add required unit for the `hold-time` Duration. Fixes parsing errors.
Fixes #376
=> Documentation; Fix for #376. Unit added for hold-time

speaker/bgp_controller.go, speaker/bgp_controller_test.go
This PR ensures that BGP announcements are withdrawn for extrernalTrafficPolicy Cluster when no healthy endpoint is available. This is essential for geo redundancy setups with multiple datacenters, where traffic should be automatically shifted via BGP to the fail over datacenter when a service gets unhealthy. 
Fixes #312 
The largest addition is `healthyEndpointExists`, which mostly is a copy of `nodeHasHealthyEndpoint`, but without the filtering on a specific node. The logic is the same. 
The real change is the `else if` branch in `ShouldAnounce`.
=> Withdraw announcement w/o healthy endpoints for TrafficPolicy Cluster

helm-chart/README.md
You had `cidr` (the old configuration key) instead of `addresses`, (the new configuration key) in the README.md file.
Fixes #
=> incorrect configuration instructions in README.md

internal/bgp/bgp.go, speaker/bgp_controller.go
This may be necessary in a true ipv6-only cluster if there are no ipv4 addresses and no router-id is specified by configuration.
Since the router-id is generated there is a probability for collisions. This is however very small and (more important) predictable beforehand. Since the router-is's are dependent on hostname only and totally deterministic it is easy to write an offline program that with 100% accuracy can tell if there will be a collision given the hostnames as input.
See also; https://github.com/projectcalico/calico/issues/2229
A step towards fix for #7 
**Special notes for your …
=> Generate a router-id from a hash on the hostname as fallback

website/content/tutorial/kubeadm-dind-cluster.md
Current MetalLB tutorials don't show how it works with a multinode cluster environment.
Using kubedam-dind-clusters allow to test MetalLB with multinode environments and can open a lot of possibilities to test different topologies and to set up new e2e tests.
Fixes #
https://github.com/google/metallb/issues/192
I reused most of the wording and code from the minikube tutorial to make it easy to follow and to compare. If you feel that's not appropriate I can redo it with my own words.
=> Add tutorial with a multinode k8s cluster using kubeadm-dind-cluster

helm-chart/templates/psp.yaml, helm-chart/templates/rbac.yaml, helm-chart/templates/speaker.yaml, helm-chart/values.yaml, manifests/metallb.yaml
Add PodSecurityPolicy to Helm chart and rendered manifest. For clusters with a PSP admissions controller, the default Capabilities will prevent the Speaker daemon set from running.
Capabilities were tested with eBFP tracing on Speaker, `NET_ADMIN` and `SYS_ADMIN` are required (on my `x86_64` CentOS 7 cluster anyway). In actual testing, the caps don't really matter because the process is running as root, they only need to be set so the policy can be selected properly. `RunAsUser` has been left as any until the image itself is able to use a non-root user. This should be tightened up when possible.
Also fixed a bug in the Makefile so `sed` on Mac works. Spacing between template blocks is still kinda weird and it's …
=> Support for PodSecurityPolicy

helm-chart/README.md
Updating Helm Chart Readme with correct config parameter for `values.yaml`, which is `configInline`, not `config` (which is what it would be called for a straight `ConfigMap` definition).
issue](https://github.com/google/metallb/issues/new) first, and get
accepted.
#<issue number>" in the …
=> Updating Helm Chart Readme

website/content/tutorial/minikube.md
Changed labels chosen to get log output as it was choosing wrong label.
=> Tutorial: Wrong label used to get log output

website/content/tutorial/minikube.md
Was running through the tutorial for BGP mode on minikube and saw that the ASNs in the snippet were incorrect compared to the tutorial-1.yaml manifest. This should fix that.
=> Update the ASNs to match the tutorial-1.yaml manifest

internal/k8s/k8s.go, speaker/main.go
MetalLB exposes its metrics on every public endpoint, because the host port is used.
However it is desirable to reduce this to e.g. the internal node IP.
This PR adds the capability to specify the listener host address of the speaker metrics.
Both a flat `--host` and the environment variable `METALLB_HOST` can be used. The environment variable can then be automatically populated via:
```
- name: METALLB_HOST
valueFrom:
fieldRef:
fieldPath: status.hostIP
```
A public image we used for testing can be found here: https://hub.docker.com/r/trevex/speaker
=> Add ability to configure metrics host address.

website/content/installation/clouds.md
I've been using MetalLB successfuly on [Vultr](https://www.vultr.com/) for the past few weeks. They [support BGP](https://www.vultr.com/features/bgp/) on all their virtual products in all locations. Setup was a breeze, it really "just worked".
I made amendments to the OVH listing as well, as I have been using MetalLB in Layer2 mode with a [vRack](https://www.ovh.com/world/solutions/vrack/) for quite some time. It requires that you purchase an IP block add it to the vRack, but after that you can use the IPs in an address pool with no problems so far.
Thanks for the hard work on MetalLB!
=> Documentation: update provider list

website/content/usage/_index.md
This small change is self-explanatory. Admittedly, I copy/pasted this value and it bit me.
=> Documentation: fix loadBalancerIP casing on usage page

manifests/kustomization.yaml
Adding the kustomization file will allow people using [kustomize](https://github.com/kubernetes-sigs/kustomize/) to point directly to upstream repository.
```
resources:
- github.com/remche/metallb//manifests?ref=v0.7.3
```
Notes :
- If we want to be able to use the `ref=v0.7.3` notation, you will have to rewrite tags. We can wait v0.8.1 though ;)
- I will write a small doc if PR is merged.
=> add kustomization manifest

controller/controller_test.go, controller/service.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go
=> Add dual-stack support in the controller

manifests/metallb.yaml
MetalLB seems already ready for k8s 1.16.
But I think, it is better to update the API group of PodSecurityPolicy in roles.
ref #458
=> Fix the apiGroup of PodSecurityPolicy in Roles

speaker/main.go
Fixed https://github.com/metallb/metallb/issues/471
I noticed that SetBalancer in Announcer.go essentially short circuits if the load balancer is already set. I also saw that it was cached in main.go of the speaker for the service.
So to fix this, I just deleted the existing balancer for the service and allowed it to fall through and create a new one with the new IP.
=> Fix layer2 not arping when IP changes

manifests/kustomization.yaml, manifests/metallb.yaml
Metallb is now using `kustomize` to generate Kubernetes resource files since [v0.8.3](https://metallb.universe.tf/release-notes/#version-0-8-3)
I noticed that in the manifest directory both `namespace.yaml` and `metallb.yaml` contain the same namespace resource, but `metallb.yaml` does not need the namespace resource if `kustomization.yaml` merge both files.
It does not only reduce codes but also beneficial for the users who want to use `metallb` resources in a different namespace. 
(They do not need to edit the upsteam yaml file and only need to edit `kustomization.yaml`)
Therefore, this pull request made the following changes.
- delete namespace resource from `metallb.yaml`
- modify `kustomization.yaml` to  merge `metallb.yaml` and `namespace.yaml`
=> modify kustomization.yaml

website/content/installation/_index.md
since v9.0 because of kustomize "metallb.yaml" doesn't have namespace spec
before apply metallb.yaml should apply namespace.yaml first
Installation page is for new user and someone just copy and paste tutorial
before v9.0 tutorial works fine
after v9.0 user will see namespace not found error
please check my PR
=> update Installation by manifest script

e2etest/manifests/mirror-server.yaml, tasks.py, website/content/community/_index.md
Fixes https://github.com/metallb/metallb/issues/552.
This PR updates the dev environment following recent changes to the MetalLB code and k8s manifests. It also updates `tasks.yaml` for kind `v0.7.0`.
To test the PR, ensure you have kind `v0.7.0` installed, then run `inv dev-env`.
P.S. Should we mention the kind dependency in the docs somewhere? I had to guess the required version in order to get `inv dev-env` to work...
=> Update dev environment

website/content/configuration/troubleshooting.md
I recently ran into an issue where I had a LoadBalancer service that had pending endpoints.  MetalLB was not responding to any ARP requests, but I couldn't see where the issue was (I didn't notice that the endpoints were pending until someone in the Slack channel pointed it out).
This commit indicates that while troubleshooting, you should check that the LoadBalance service has endpoints that are not pending.
Hopefully it will save someone the 10+ hours I spent debugging this issue (and committing the cardinal sin of asking for help in [issues](https://github.com/metallb/metallb/issues/560)) until someone on the Slack channel figured out where I was going wrong!
=> Website: Add extra troubleshooting steps to the website

website/content/community/release-process.md, website/content/installation/_index.md
This patches were created some weeks ago when doing the 0.9.x release, of the random things I noticed I did differently from the release process document.
There is also a simple fix to reference metallb github org in the install instructions. Actions to do that thoroughly are already in progress (https://github.com/metallb/metallb/pull/570 and https://github.com/metallb/metallb/issues/567), this is just an old patch that I had in my queue.
More details in the commit messages :)
=> Fix website typos on release process

manifests/metallb.yaml, speaker/main.go
Docker EE already uses port 7946 (likely memberlist)
Fixes #581
=> Add ml-bindport / METALLB_ML_BIND_PORT config

speaker/main.go
New log looks like:
{"caller":"net.go:785","component":"MemberList","msg":"[DEBUG] memberlist: Initiating push/pull sync with: 10.11.12.13:7946","ts":"2020-04-17T00:31:37.51568936Z"}
=> Use go-kit log.NewStdlibAdapter instead of our own adapter

website/content/concepts/layer2.md
While reading about metallb via the web site, I noticed some content
that was out of date with the current implementation.  The layer 2
mode page still discussed the use of the Kubernetes API for leader
election.  I've updated the text to reflect that memberlist is now
used for cluster membership in metallb.
=> website: Reflect the move to memberlist

website/content/concepts/maturity.md
I'm very new to the MetalLB community, but based on my limited
experience so far, it seemed like this text wasn't quite up to date
with the current state since I've seen other maintainers handling some
PRs.
This change also links to the contributing page as a place to find out
more info on who the current maintainers are.  That information is not
there currently, but it seems like an appropriate place to add it.
=> website: Update maintainers description

tasks.py
A comma got used where a period was needed.
=> Fix small bug in tasks.py error handling

.circleci/config.yml
The config attempted to filter out PRs already, but for some reason it
didn't work.  This updated config just explicitly lists the branches
to run against: main and the v.* release branches.  This makes it skip
PRs for those jobs in my testing.
=> circleci: Update branch filters for deploy jobs

README.md
A trivial fix, but as a metallb newbie I was distracted by the broken "build" widget.  Since metallb's builds are actually passing it's a shame for other first-timers to get the wrong impression.
=> Fix the README "widgets"

tasks.py
Drop a few imports that are not used.  These were pointed out by the
flake8 utility.
=> tasks.py: Drop unused imports

.circleci/config.yml
gometalinter was previously run in the test job which runs "go test".
There should be a slight runtime improvement by moving this into its
own job, but the main reason to split it out is so it shows up as its
own status line item when results are reported back to github.  When
something fails, you will be able to more quickly determine which area
the failure is in (linting vs the tests).
=> ci: Split lint out into its own job

tasks.py, website/content/installation/_index.md
While we are there, update the github link to use the metallb org.
Fixes: #489
I've tested this locally, running the `inv release --skip-release-notes 0.9.4`. Make sure this commit is on `main` _and_ `v0.9` branch to test, though. Iit worked just fine here.
To undo the release created locally, you can run: `git checkout  v0.9 && git tag -d v0.9.4 && git reset --hard HEAD^`
There are some PRs open to update the kustomize instructions, so hopefully this might be removed soon. For now, it's better to have the proper version on new releases :)
=> tasks.py: Update kustomize version on release

controller/main.go, internal/k8s/k8s.go, speaker/main.go, website/content/community/_index.md
When you're developing, running components at the command line and
having them attach to a cluster might be more convenient than
redeploying them to a cluster over and over.
For the controller, -kubeconfig and -config-ns are needed.  Speakers
need those and -node-name.
For example:
metallb$ go run ./controller/main.go ./controller/service.go -config-ns metallb-system -kubeconfig $KUBECONFIG
metallb$ go run ./speaker/main.go ./speaker/*controller.go -config-ns metallb-system -kubeconfig $KUBECONFIG -node-name node0 …
=> Add command-line flags to run processes outside of k8s

internal/bgp/messages.go
While setting up a dev and test environment for BGP mode, I got the
following error in my speaker log:
{"caller":"bgp.go:408","error":"got BGP notification code 0x0400 (unknown code)",
"event":"peerNotification","localASN":64513,
"msg":"peer sent notification, closing session",
"peer":"172.18.0.5:179","peerASN":64512,"ts":"2020-07-22T21:20:07.673523481Z"}
0x0400 is an unspecific "Hold timer expired" notification.  The code
portion of "04" is "Hold timer expired", and the sub-code of "00"
means there is unspecific.
Update the code to provide an improved error message in this case.
The updated message is:
{"caller":"bgp.go:408",
"error":"got BGP notification code 0x0400 (Hold Timer Expired (unspecific))",
"event":"peerNotification","localASN":64513,
"msg":"peer sent notification, closing …
=> bgp: Decode hold timer expired notification

CODEOWNERS, website/content/community/_index.md, website/content/community/maintainers.md
When I first joined the MetalLB development community, I was curious
who the current maintainers were.  This patch is a proposed method of
communicating who that team is, as well as how the team is governed.
First, create OWNERS file. Nothing will actually read this file, but
it is a convenient and familiar format to list maintainers within the
Kubernetes ecosystem.
This patch also introduces a document in the community section of the
web site that discusses the group of maintainers and how people are
added or removed.
Consider this a starting point for discussion.  It's really something for the
current maintainers to decide on.
=> Document maintainership of MetalLB

.circleci/config.yml, website/content/community/_index.md
CircleCI was previously only configured to publish images for pushes
to branches or tags.  While CI runs against open PRs, the publish jobs
that published images was excluded.
This PR updates the deploy jobs to detect when they are running
against a pull request.  When run against a PR, the images are pushed
to the `metallbdev` org instead of `metallb` and the image tag is
"pr-<ID>".
The dev docs on the web site are also updated to note how to pull an
image built for a PR.
Fixes #623
=> Publish images for each open pull request

website/content/configuration/_index.md
This PR concerns issue #669 I filled about configuration problem.
And the solution was to use a CIDR notation even for a single IP.
There is my proposal to the documentation.
=> Add a note to the website about single-IP address pool

internal/config/config.go, internal/config/config_test.go
Configuring the same peer twice is an error. Configuring two identical peers results in a rapidly-flapping BGP session. This PR disallows identical peers in the configuration. In the future we may want to perform smarter checks, however at the very least this fix will catch copy-paste mistakes.
=> Disallow duplicate peers in config

website/content/configuration/_index.md
This PR improves the phrasing of the note we have in the docs about using single IP addresses.
=> website: Rephrase note about single IP addresses

CONTRIBUTING.md, DCO, website/content/community/_index.md
This commit includes a light-weight approach for MetalLB to adopt the
DCO (Developer Certificate of Origin) for contributions.  Some projects
use a `Signed-off-by:` header in commit messages as an acknowledgement
of the DCO.  In this case, we just include the DCO file and update the
contributing docs to explain that by contributing, you agree to the DCO.
Some examples of other projects that adopted this approach to using the
DCO include:
- several from github.com/coreos, such as github.com/coreos/ignition
- projects under github.com/metal3-io/
=> contributing: Adopt the DCO

internal/k8s/k8s.go, internal/speakerlist/speakerlist.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go, speaker/main.go
This PR makes the nodes join the memberlist cluster when they left for some reason (network outage, etc.).
It is based on the ideas from the RFC PR #647 but storing the Speaker IPs to also be able to recover when the API server is down (before we relied on the API server to gives us the APIs, so if it was down we couldn't join members), based on @champtar suggestion on that PR.
It consists of two commits: the first one is cherry-picked from #595 and just moves the memberlist code from `speaker/main.go` to it's own package, so it is easier to reason and abstract. The second one just adds a go routine that will try to re-join the nodes whenever it is needed.
The semantic changes in the second commit aim to be simple to follow and reason about, without any major rework. More reworks can be …
=> layer2: Make nodes re-join memberlist cluster

internal/layer2/announcer.go, internal/layer2/announcer_test.go
With our current approach, we only do gratuitous advertisements on the first
SetBalancer() call, and we don't resend any gratuitous advertisements on the next
calls to reduce the amount of "spam" in the network.
This was working pretty well when we were using K8S API to do all the decisions.
Now that we are also using MemberList status, our decisions are based on eventually consistent
information, and there are at least 2 cases where we need to resend gratuitous advertisements
even if the information that we have makes us think there were no changes in ownership:
1) Split brain with no ownership changes:
3 nodes A B C, A owns the LoadBalancer IP I, cluster is clean.
Now for some reason C can't talk to A and B anymore, and our algorithm
in ShouldAnnounce() continues to pick A as the owner …
=> Rework how gratuitous advertisements (ARP/NDP) work

manifests/metallb.yaml
According to kubernetes documentation, since v1.19 kubernetes stops using labels with "beta." prefix. Installation manifest manifests/metallb.yaml fixes nodeSelector to kubernetes.io/os.
Fixed   #743
=> Update manifests/metallb.yaml for kubernetes v1.19

.github/pull_request_template.md, speaker/main.go, tasks.py, website/config.toml, website/content/_index.md, website/content/community/_index.md, website/content/concepts/layer2.md, website/content/configuration/_index.md, website/content/configuration/calico.md, website/content/faq/_index.md, website/content/installation/clouds.md, website/content/installation/network-addons.md, website/content/release-notes/_index.md, website/content/usage/_index.md
Supersedes #570. Fixes #567.
Opening a new PR as we needed to rebase and I couldn't push to the original branch, likely because the fork no longer exists.
=> Update repository URLs

tasks.py, website/content/community/_index.md
This PR updates kind to the current latest version - `v0.9.0` which also uses k8s `v1.19` by default.
=> Update kind to v0.9.0

tasks.py
Our CI environment uses Python 2 which doesn't support f-strings. We should update to Python 3 but in the meantime we need a working CI.
This wasn't caught before merging because we don't push images for PRs.
=> dev-env: Fix syntax

e2etest/manifests/mirror-server.yaml, manifests/metallb.yaml, tasks.py, website/content/community/release-process.md
This PR points the manifests to Quay instead of Docker Hub.
Fixes #696.
=> Move images to Quay

manifests/metallb.yaml, tasks.py
There is no reason to have it set to Always and re-pulling the image every time can make k8s convergence and scaling slower.
Fixes #748.
=> Set imagePullPolicy to IfNotPresent

netlify.toml
This should fix the Netlify links to older releases under https://metallb.universe.tf/release-notes/.
=> website: Fix Netlify publish dir

manifests/metallb.yaml
Even if not required it's better to properly document what is used as ports
=> manifests: add memberlist ports

manifests/metallb.yaml
Those capabilities are not needed and allow to break out of the container
This was introduced in a18378a3359284da08acdae4cdb134f8376019ed / #382
Fixes #762
=> Remove NET_ADMIN and SYS_ADMIN capabilities

controller/controller_test.go, controller/main.go, internal/k8s/k8s.go, manifests/metallb.yaml, speaker/bgp_controller_test.go, speaker/main.go
The Update() to the Service object is never triggered because the code
does not modify the object between the deep copy and when Update() is
called.
Previously, commit cdd44aa9 ("Initial commit. Somewhat working
controller, half-written BGP speaker") modified the Spec and Annotations
field of the Service. However, since commit 3e10f6ea ("Clean up processing
to exclusively use status.loadBalancer.ingress.ip"), that is no longer
the case, as the code exclusively only touches the Status field.
Therefore, this commit removes this dead code and revokes the update
privileges from the ClusterRole as well.
Signed-off-by: Chris Tarazi <chris@isovalent.com>
=> Remove unused Service Update()

manifests/metallb.yaml
I've experienced issues in the past where MetalLB was throttled
for 15s and then replying to all previous ARP request at the same time.
MetalLB is the entry point of the cluster, if it's not working everything
else in the cluster is useless, so let's just not set limits.
=> Do not set resources limits by default

website/content/_header.md
When I try to run `hugo server` right now, I get the following error:
Error: Error building site: "/home/rbryant/go/src/github.com/metallb/metallb/website/content/_header.md:1:1": plain HTML documents not supported
It seems like this is an issue with a more recent version of hugo.
I'm using the following version from a Fedora package:
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown
This change is based on a suggested workaround in the following issue:
https://github.com/gohugoio/hugo/issues/7296
The workaround seems harmless, and may no longer be needed if the
following issue gets resolved at some point in the future:
https://github.com/gohugoio/hugo/issues/6098
=> website: Fix a hugo error

.circleci/config.yml, tasks.py
Since inv is used to run other dev workflows, add another task to run
the unit tests.  Also update CircleCI config to use inv to run the
tests so that we keep the local dev commands in sync with what runs in
CI.
=> inv: Add task to run unit tests

.gitignore
We should remove the e2etest references as these were dropped.
=> gitignore: Update .gitignore to remove e2etest reference

speaker/main.go, website/content/release-notes/_index.md
This is the value used in the manifests
=> Set default prometheus port to 7472 for speakers

design/README.md, website/content/community/_index.md
To allow for easier review on design proposals, create a directory for
design proposals.  Future PRs with proposed designs should be posted as
a PR to this directory.
While we don't require a specific outline, we encourage the use of the
KEP template for inspiration.
=> design: Create a directory for design proposals

.circleci/config.yml, tasks.py
Prior to this change, every time you ran the `vtysh` command in the
`frr` container when using the bgp dev environment, you would get an
error about `vtysh.conf` missing.  The error is misleading and makes
it seem like something is wrong.
Create an empty config file to suppress this error message.
Closes #713
=> dev-env: Create vtysh.conf

.circleci/config.yml, .github/workflows/release-chart.yaml, charts/metallb/.helmignore, charts/metallb/Chart.yaml, charts/metallb/README.md, charts/metallb/policy/controller.rego, charts/metallb/policy/rbac.rego, charts/metallb/policy/speaker.rego, charts/metallb/templates/NOTES.txt, charts/metallb/templates/_helpers.tpl, charts/metallb/templates/config.yaml, charts/metallb/templates/controller.yaml, charts/metallb/templates/podmonitor.yaml, charts/metallb/templates/prometheusrules.yaml, charts/metallb/templates/psp.yaml, charts/metallb/templates/rbac.yaml, charts/metallb/templates/service-accounts.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, ct.yaml, tasks.py, website/content/installation/_index.md, website/content/release-notes/_index.md
Create a new helm chart integrating features of the previous chart, as
well as stable/metallb and bitnami/metallb.
Features:
* Support new environment variables in speaker
* Use PodMonitor instead of ServiceMonitor (no need to create Services)
* Create PrometheusRule to detect stale config and config-not-loaded
* Configurable PrometheusRule alerts for address pool exhaustion
* Support MetalLB controller creating memberlist secret
* Standardize labels using template helper
* Create config-watcher and pod-lister roles
* OPA/rego based chart output validation
* JSON Schema values validation
Fixes metallb/metallb#653
=> Re-add helm chart under charts/metallb

charts/metallb/values.schema.json, charts/metallb/values.yaml
.Values.prometheus.* underwent several re-writes during chart
development, the values.schema.json for this had fallen behind.
Changes:
* enforce labels are strings for prometheusAlert objects
* validate .Values.prometheus.podMonitor.*
* move PrometheusRule values from .Values.prometheus.* to
.Values.prometheus.prometheusRule.*
* Clean up comment in values.yaml
* Fix type of .Values.prometheus.podMonitor.interval in values.yaml
Depends on #841
=> chart: clean up values schema of .Values.prometheus.*

.circleci/config.yml, go.mod
Golang 1.13 has horrible bugs that might have affected MetalLB
as it's using client-go / watches,
see https://github.com/kubernetes/kubernetes/issues/87615
Newer client-go version (that we are now using) have implemented
HTTP/2 health check by default but this is a workaround not a fix.
Also Golang 1.13 is not supported anymore
This replace #816
=> Bump Golang to 1.16

.circleci/config.yml, .golangci.exclude, .golangci.yml, internal/allocator/allocator.go, internal/bgp/bgp.go, internal/config/config.go, internal/k8s/k8s.go, internal/layer2/announcer.go, internal/speakerlist/speakerlist.go, speaker/layer2_controller_test.go, speaker/main.go, tasks.py
In the process of adding a linter task to `tasks.py`, I discovered that `gometalinter` has been deprecated. This PR adds that task and migrates the linter.
=> Migrate linter from gometalinter to golangci-lint

internal/allocator/allocator.go
Trivial fix to provide reason for sharing key failure.
=> Wrap sharing key error

website/content/installation/network-addons.md
I've been using [kube-ovn](https://github.com/kubeovn/kube-ovn) with MetalLB in BGP mode for about a year and no issues so far.
=> Add kube-ovn to list

.circleci/config.yml, tasks.py
In order to triage CI failures, we store the output of kind export logs to circle CI.
=> Store kind logs in circleci

design/metallb-operator.md
This proposes creating a new repository under the metallb github
organization to allow interested parties to collaborate on an operator
as an alternative method for managing the deployment of MetalLB on a
cluster.
=> design: Propose a MetalLB operator

tasks.py
The release process script has a regex for fixing image references in
manifests, but these were not updated to reflect the move to quay.io.
This change updates it so the image reference will properly get updated
on the next release.
Fixes #874
=> release: Fix image reference regex

tasks.py
Fixed #879 
Unit-test
```
git checkout v0.10
inv dev-env
image: quay.io/metallb/speaker:dev-amd64
image: quay.io/metallb/controller:dev-amd64
git checkout main
inv dev-env
image: quay.io/metallb/speaker:dev-amd64
image: quay.io/metallb/controller:dev-amd64
```
Metallb generated manifests will change image's tag from v0.10.1 to dev-amd64
=> Allow running dev-env from any branch

tasks.py
When trying to run `inv e2etest` against an unconfigured dev-env,
the following message is displayed.
`
Encountered a bad command exit code!
Command: "kubectl get configmaps -n metallb-system config -o jsonpath='{.data.config}'"
Exit code: 1
Stdout:
Stderr:
Error from server (NotFound): configmaps "config" not found
`
This message does not clearly explain the problem. This commit
resolves this by providing a helpful message.
Fixes: 4e9ceccf9f06 ("tasks.py: circle ci does not fail on e2etest failure")
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> e2etest: Display error message when testing unconfigured dev-env

e2etest/bgp_test.go, e2etest/layer2_test.go, e2etest/utils.go
Add wget retries (4 attempts) to layer2 and bgp e2e tests, which was mentioned during the review of PR #882 
Unit-Test:
[unit-test-program](https://play.golang.org/p/TJTfphar8g4)
=> Add wget retries to both layer2 and bgp e2e tests

charts/metallb/templates/controller.yaml, charts/metallb/values.yaml, manifests/metallb.yaml, website/content/release-notes/_index.md
Fixes #890
we need to set fsGroup for the controller to read the k8s api token.
=> Add fsGroup to controller deployment

charts/metallb/Chart.yaml
These versions get updated automatically as part of the release process.
This will update release branches and tags, but never in main. To avoid
confusion, just leave the version as 0.0.0 in main, along side the
comment that says this is updated automatically.
=> charts: Clear version in Chart.yaml in main branch

e2etest/bgp_test.go, e2etest/e2etest_suite_test.go, e2etest/layer2_test.go, e2etest/utils.go, tasks.py
This change enables to run e2etest in non kind deployments
- parameterize kubeconfig and system namespace
- add option to change port of Pod because some distribution cannot open port tcp/80 in pod due to security considerations
This PR is for #884
=> Change e2etest for non kind clusters

charts/metallb/values.schema.json
imagePullSecrets is an array of objects with a single property "name"
Fixed #897
=> chart: fix validation of .Values.imagePullSecrets

internal/bgp/bgp.go, internal/config/config.go, internal/config/config_test.go, manifests/example-config.yaml, speaker/bgp_controller.go, speaker/bgp_controller_test.go, website/content/configuration/_index.md
This is a follow up for #672.
TODO:
>NOTE: There doesn't seem to be an easy way to test the source address functionality. We would likely need to do some significant refactoring to the tests and possibly to the way we deal with BGP sessions in the code itself.
Fixes #670.
=> Make BGP source address configurable

internal/k8s/k8s.go
This is causing unnecessary work and log spam
Fixes #901 
Fixes #899
=> Set resyncPeriod to 0 for EndpointSlice NewIndexerInformer

website/content/community/_index.md, website/content/community/release-process.md, website/content/configuration/romana.md, website/content/configuration/troubleshooting.md, website/content/faq/_index.md, website/content/installation/_index.md, website/content/installation/clouds.md
Fixed #857
* Use `bash` instead of `shell`.
* Use `ini` on the Romana page. It's fishy, but the
appearance is OK.
* Add `yaml` to a few and swap a few `yaml` to `bash`.
=> fix: Specify type for fenced code blocks

charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, controller/main.go, controller/service.go, internal/bgp/bgp.go, internal/k8s/k8s.go, internal/layer2/announcer.go, internal/layer2/arp.go, internal/layer2/ndp.go, internal/logging/logging.go, internal/speakerlist/log.go, internal/speakerlist/speakerlist.go, manifests/metallb.yaml, speaker/bgp_controller.go, speaker/main.go, website/content/release-notes/_index.md
Signed-off-by: Utku Ozdemir <uoz@protonmail.com>
This PR implements leveled logging. I set the levels as I've seen fit by looking at their messages - any feedbacks are appreciated.
Fixes #254 
Fixes #655
=> Implement leveled logging

tasks.py
`inv lint` is currently broken:
```
docker run --rm -v $(git rev-parse --show-toplevel):/app -w /app golangci/golangci-lint:v1.39.0 golangci-lint run $(git rev-parse --show-toplevel)/...
level=error msg="[linters context] typechecking error: pattern /tmp/metallb/...: directory prefix /tmp/metallb outside available modules"
level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1009: failed prerequisites: [errors in package: [-: pattern /tmp/metallb/...: directory prefix /tmp/metallb outside available modules] errors in package: [-: pattern /tmp/metallb/...: directory prefix /tmp/metallb outside available modules]]"
level=error msg="Running error: S1009: failed prerequisites: [errors in package: [-: pattern /tmp/metallb/...: directory prefix /tmp/metallb outside available …
```
=> Fix `inv lint`

.github/workflows/commitlint.yaml, commitlint.config.cjs
This PR enforces some rules around commit message style. I find it useful because I find myself commenting on commit style repeatedly in code reviews and it's easier to let a machine enforce at least some rules.
I've opted for GitHub Actions because it was very tricky to get `commitlint` to work in CircleCI and in Actions it just works :tm: 
A sample result of the new linting job can be seen in the status of this PR.
=> Enforce commit message style

design/0001-frr.md, design/speaker.md
This design document discusses integration of FRR as an
alternative BGP agent implementation for MetalLB.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
=> design: BGP FRR integration

website/config.toml, website/content/community/_index.md
Github is more accurately referred to as GitHub.
=> Fix typo on website

.circleci/config.yml, tasks.py
fix: build multi arch images from base up
currently busybox is in sync with build platform arch
so let's sync it to the target platform arch.
this will enable users to enter running containers
without getting arch driven errors. (#618)Thanks for sending a pull request! A few things before we get started:
Fixed #618
=> multiarch fix

controller/main.go, internal/k8s/k8s.go, speaker/main.go
As discussed in https://github.com/metallb/metallb/issues/936 there are certain scenarios where endpointslices are technical available but should not be used by metallb.
This PR adds a config flag to disable the usage of endpointslices completely. If the flag is not provided the behaviour is the same as before.
=> Add config flag to disable usage of endpointslices

website/content/community/_index.md
Commit 51bfb61 consolidated several namespace options into one
('namespace'/'METALLB_NAMESPACE'). This commit fixes a leftover in the
website.
=> Fix namespace parameter name

artifacthub-repo.yml
Contains artifacthub.io metadata according to requirements here:
* https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories
* https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml
I've included my own name/email on the owners list.  We should add other maintainers as well.
Fixed #875
=> chart: add artifacthub-repo.yml

.circleci/config.yml
Add an empty circleci configuration to this branch to avoid circleci
reporting failures against this branch.
=> gh-pages: Add empty circleci configuration

charts/metallb/templates/podmonitor.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, manifests/prometheus-operator.yaml
When using metallb in combination with the prometheus operator, we need to grant prometheus permission to read the pods.
Here, we fix that by creating the required role / rolebinding.
On top of that, a new `prometheus-operator.yaml` manifest is created under manifests to allow the same configuration when deploying from manifests.
=> Fix PodMonitor rbac

.circleci/config.yml, dev-env/bgp/config.yaml.tmpl, dev-env/layer2/config.yaml.tmpl, e2etest/bgp_test.go, tasks.py
Here we add an option to specify the ipfamily of the kind cluster, we use it for CI and we adjust the tests / configuration to run against ipv6 only clusters.
=> Add ipv6 / dual stack lanes

internal/config/config.go, internal/config/config_test.go
An AddressPool where the first address of the range is after the second
should be an invalid range. In such case the LoadBalancer service is
unable to get an IP.
The service is not getting an ip with the following error:
`{"caller":"level.go:63","error":"no available IPs","level":"error","msg":"IP allocation failed","op":"allocateIP","service":"default/nginx","ts":"2021-09-13T08:40:02.487727369Z"}`
```
$ kubectl get service -A
NAMESPACE     NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       nginx        LoadBalancer   10.96.240.166   <pending>     80:32319/TCP             53s
```
=> Add AddressPool validation check for invalid ranges where first address of the range is after the second

e2etest/bgp_test.go, e2etest/layer2_test.go, e2etest/pkg/executor/executor.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/parse.go, e2etest/pkg/frr/parse_test.go, e2etest/pkg/frr/validation.go, e2etest/pkg/routes/routes.go, e2etest/utils.go, go.mod
Currently, BGP test only verifies that the remote peer can hit the service. We don't have guarantee that all the ip is advertised from all the nodes and that the BGP sessions are established.
Here we add helper packages to check both, providing a base for adding more testcases.
The frr parsing utilities are in a package of their own, and may be useful if parsing the FRR output is needed to provide status feedback or metrics.
=> Extend BGP test to check routes and session state

e2etest/pkg/frr/parse_test.go
The result is fetched as the iteration of a map, making the result unpredictable. Here we sort the result so the unit test is stable.
Also, removed unnecessary println.
=> TestNeighbours unit test: sort neighbours before checking

dev-env/bgp/config.yaml.tmpl, e2etest/bgp_test.go, e2etest/pkg/metrics/metrics.go, e2etest/pkg/metrics/metrics_test.go, go.mod
We extend the e2e tests with one test that validates the presence of the current metrics, create a service and checks the service announcement metrics.
This may require some rework when https://github.com/metallb/metallb/pull/931 lands.
=> Add bgp metrics tests

design/0001-frr.md
Sending this as discussed with @markdgray . 
The enhancement proposal mentions extending the current e2e test suite.
Here, we provide a list of the coverage needed to ensure compatibility between the old implementation and the new implementation.
This is meant to be a starting point for defining the list of our tests. I think it's a good start, and meant to start a discussion to understand if new scenarios need to be added.
=> Extend the frr enhancement proposal with the list of tests

internal/config/config.go, internal/config/config_test.go
Hi, the check introduced in 0.11.0 leads to a problem if you specifiy exactly one IP in your metallb IP pool
`{"caller":"level.go:63","configmap":"metallb-system/metallb","error":"parsing address pool #1: invalid CIDR \"192.168.1.210-192.168.1.210\" in pool \"default\": invalid IP range \"192.168.1.210-192.168.1.210\": start IP \"192.168.1.210\" is after the end IP \"192.168.1.210\"","event":"configStale","level":"error","msg":"config (re)load failed, config marked stale","ts":"2021-10-29T17:54:47.659792734Z"}`
=> fix invalid IP range check for exactly one IP

website/content/community/_index.md
We used to enforce a line length limit via CI, but turned that off due
to breaking long links in commit messages. At least document the
requirement in our contributing page.
=> contributing: Add commit message guidelines

.circleci/config.yml, internal/bgp/frr/config.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden, manifests/metallb-frr.yaml, speaker/Dockerfile, tasks.py
This PR connects the dots in FRR integration by collecting the remaining bits from https://github.com/metallb/metallb/pull/969 and:
- adding the reloader to the speaker image
- implementing the reload function
- adding a metallb_frr.yaml manifest to deploy metallb in frr experimental mode
- adding a CI lane that tests bgp in frr mode
=> Metallb FRR integration

.circleci/config.yml, e2etest/bgp_test.go, e2etest/pkg/frr/parse.go, manifests/metallb-frr.yaml
While fixing comments in https://github.com/metallb/metallb/pull/1014 , I cherry-picked a wrong version of the frr manifest, with the result that CI is running legacy mode even on the CI lanes (this is what we call volkswagen test https://github.com/auchenberg/volkswagen)
Here, we fix the manifest and we add a test (running only on the frr lanes) that validates the FRR container in the pods is actually working.
=> Fix FRR manifest

e2etest/bgp_test.go, e2etest/e2etest_suite_test.go, e2etest/pkg/executor/executor.go, e2etest/pkg/frr/container.go
We want to be able to run the tests against a real cluster and not only against kind, and to use podman too to run the e2e tests.
=> Allow running FRR container on host network when running e2e tests 

manifests/metallb-frr.yaml
The native bgp implementation does not listen on a bgp port,
meaning it is always the side initiating the BGP connection.
We should mimic this behavior in FRR mode as it preserves some
of the peer's configuration by using:
https://docs.frrouting.org/en/latest/bgp.html#cmdoption-bgpd-p.
For example peer-port: without this change there is no guarantee
that it is actually used for the connection - the other side might
be initiating it hence the peer's port will be random from the speaker's side (TCP).
=> FRR: Don't listen bgp port

e2etest/bgp_test.go, e2etest/config/frr/daemons, e2etest/e2etest_suite_test.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/consts/consts.go, e2etest/pkg/frr/container/container.go, go.mod, internal/bgp/frr/config.go, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
Currently the tests run using one external BGP peer.
Running multiple external BGP peers allows us to cover
more scenarios in parallel such as internal/external BGP
and multiple MyASNs. In addition, doing it in a configurable
way will allow us to extend the tests to cover more scenarios
in the future by shuffling configuration for the speaker
and the external containers that serve as BGP peers.
=> Run tests with multiple configurable FRR containers

website/content/community/release-process.md
Note that we must manually publish an update to the helm chart. Also
note that the version number should be updated in #metallb on slack.
=> release-process: add notes on helm and slack

controller/controller_test.go, controller/main.go, internal/k8s/k8s.go, speaker/main.go
When applying changes in bulk, a change in a service may be received / processed asynchronously from the configuration. We may want to be able to reprocess the configmap later, when the service is deleted.
=> Speaker: reprocess the configuration when the ip assigned to services

e2etest/e2etest_suite_test.go, e2etest/layer2_test.go
Currently the ports are hard coded in the test and therefore it is
failing in clusters where this port is not allowed.
Doing this will allow running this test based on the passed base port
by the user, which should be open.
=> L2 E2E: Set service port based on service-pod-port flag

e2etest/config/frr/bgpd.conf, e2etest/pkg/frr/config/config.go
Here we render directly the bgpd conf and write it removing one extra jump through templates.
=> E2E: write the config directly instead of using templates

internal/bgp/frr/frr.go, manifests/metallb-frr.yaml
user can overwrite the default logging level if needed via envvar settings
=> Export MetallB FRR logging as envvar in FRR manifest

e2etest/bgp_test.go, e2etest/layer2_test.go, internal/k8s/k8s.go
The current method did not work properly for IPv6:
```
"err":"listen tcp: address fc00:f853:ccd:e793::4:7472: too many colons in address",
"host":"fc00:f853:ccd:e793::4","level":"error","msg":"cannot listen and serve",
"op":"listenAndServe","port":7472
```
Using net.JoinHostPort to handle both IPv6 and IPv4 solves this.
In addition this PR fixes a small bug in the BGP tests and adds metrics tests for L2.
Having coverage only for BGP metrics caused the CI
to miss the listen bug above +
We should also cover the L2 metrics anyways.
=> Fix metrics listen and add test coverage for layer2 metrics

e2etest/pkg/frr/config/config.go, internal/bgp/bgp.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalid.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden, internal/bgp/native/native.go, internal/config/config.go, internal/config/config_test.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go
Added BGP peer keepalivetime configuration option
the current metallb stack assumes its always 1/3 of the holdtime while this the recommended default setting by rfc4271 but it doesn't have to stay like that, this change export the config option so FRR can make use of it while not changing the current
keepalive alg used by Metallb native stack.
=> Add keepalivetime configuration option to metallb

charts/metallb/templates/podmonitor.yaml, charts/metallb/templates/rbac.yaml, charts/metallb/values.yaml
Addresses namespace issues raised in #1048
1. Remove `.metadata.namespace` from resources, helm should generate thes
2. Remove default values of `.Values.prometheus.serviceAccount` and `.Values.prometheus.namespace`, we should not assume what users default values of these are.  Validate them with the `required` function instead.
```
$ helm lint .
==> Linting .
1 chart(s) linted, 0 chart(s) failed
$ helm lint . --set prometheus.podMonitor.enabled=true
engine.go:167: [INFO] Missing required value: .Values.prometheus.serviceAccount must be defined when .Values.prometheus.podMonitor.enabled == true
engine.go:167: [INFO] Missing required value: .Values.prometheus.namespace must be defined when .Values.prometheus.podMonitor.enabled == true
==> Linting .
1 chart(s) linted, 0 chart(s) failed
$ …
```
=> Helm chart namespace fixes

e2etest/e2etest_suite_test.go, e2etest/parse_config.go
When installing MetalLB with Helm the configmap name should be `metallb` and not `config`. To run the e2etests we should be
able to set the config map name.
=> Allow setting the configmap name when running e2etests

website/content/configuration/_index.md
When installing MetalLB with Helm the config map name should be `metallb` and not `metallb-config`.
=> Fix the configmap name in the website doc for MetalLB install with Helm

.circleci/config.yml, tasks.py
Adding an option to set the log level for both the
speaker and the controller.
Setting the `all` level for CI should help us with debugging
failed tests.
=> WIP: Add log_level flag to dev-env

e2etest/bgp_test.go, e2etest/layer2_test.go, e2etest/pkg/metrics/metrics.go
We should use the testNameSpace variable all over the tests code to run the tests in the right namesapce.
=> Fix e2etests to use the namespace variable

manifests/metallb-frr.yaml
Currently the FRR logs aren't visible when running kubectl logs
(even when running in stdout logging mode) because the daemons run
under frr:frr and their stdout differs from watchfrr's (that runs
under a different user).
Bypassing this by tailing the log file seems good enough,
we could change this later if needed.
=> FRR: Have FRR logs visible when running kubectl logs -c frr

.github/workflows/fossa.yaml
During CNCF onboarding, we were advised to adopt an automatic license
checking tool. This PR enables running FOSSA against MetalLB PRs.
issue #1060
=> ci: Add FOSSA license checking

.circleci/config.yml, e2etest/layer2_test.go, e2etest/pkg/mac/mac.go
Getting a lot of flakes in the CI:
```
Expected
<*errors.errorString | 0xc000695790>: {
s: "metric metallb_layer2_requests_received not found",
}
to be nil
```
It is caused by the fact that this metric represents the amount
of ARP/NS that arrived to the speaker for the svc's ip, while the
test doesn't necessarily does one. That can happen because the speaker
sends a gratuitous message when he announces an IP.
Also added a check for the gratuitous_sent metric to cover that.
=> Fix L2 metrics tests

e2etest/bgp_test.go, e2etest/pkg/executor/executor.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/metrics/metrics.go
In order to ease debugging, we dump the state of the external frr container in case of failure.
We also invert the order of beforeEach / afterEach and the framework creation so that our afterEach is registered before the framework's one and the namespace is not deleted when we bump.
=> E2E: Dump the frr configuration in case of test failures

README.md
The old section still contained Dave Anderson's email as the primary destination, it's sane to correct it.
=> Update the security reporting recipients.

README.md
CII best practice badge is required as part of the CNCF approval process.
=> Add the CII best practices badge

README.md
This was just set up and the initial report is full of false positives
that need cleanup. Remove the badge until the report it represents is
deemed accurate.
=> readme: Remove fossa badge

e2etest/bgp_test.go, e2etest/layer2_test.go
1. Fix the error message produced when no controller pod found.
2. Add a validation to check at least one speaker pod found.
3. Use getSpeakerPods function to avoid code duplication.
=> E2e tests code improvements

.circleci/config.yml
The change permission command is skipped if the tests fail, which makes the export of some logs fail. We want the command to always be executed, in particular when tests fail.
=> CI: change the permissions on kind logs when tests fails

e2etest/config/frr/bgpd.conf, e2etest/config/frr/zebra.conf, e2etest/pkg/frr/config/config.go
Aims to fix a flake where BGP is not able to start, showing messages as
```
BGP: [EC 33554499] sendmsg_nexthop: zclient_send_message() failed
```
the current-config is as well empty, so it could be an issue related to the order in which bgp starts / the tests place a config under its hood. 
Here we start with a valid config that gets eventually overridden by the tests.
=>  E2E: Add an empty bgpd.conf file with zebra password

.circleci/config.yml, e2etest/bgp_test.go, e2etest/layer2_test.go, e2etest/pkg/routes/routes.go, e2etest/pkg/service/tweak.go
Instead of driving the ipfamily from outside, we use the family of the loadbalancer ip to derive what family it is, and we use both in case of dual stack services.
We add more entries to the test tables forcing the service to be dual stack in case of dual stack entries, and adding extra entries to check single v6 in case of dual stack (for the v4, we defer to the fact that a service gets created as single stack v4 in case of dual stack).
Additionally, the old ipFamily parameter is now used to choose the ipfamily of the pairing between the external FRRs and the speakers, making it possible to test scenarios where we advertise v6 addresses on a v4 connection and viceversa.
=> E2E Test: provide support for dual stack

website/content/installation/clouds.md
Add another requirement for a change needed to be done to run
MetalLB on OpenShift. 
By also deleting the `spec.template.spec.securityContext.fsGroup` in the metallb manifest 
It's because currently, in the manifests, the fsGroup value is 65534 which is out of range 
for Openshift (5000 - 5999).
=> website: Update installation on Openshift instructions

e2etest/bgp_test.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go, e2etest/pkg/frr/validation.go, e2etest/pkg/k8s/nodes.go, e2etest/pkg/routes/routes.go
Instead of connecting via a single protocol for both families (ie v4 for advertising both v4 and v6), we create two peers, one for each family.
=> E2E tests dual stack: have a peer for each family

.circleci/config.yml, controller/controller_test.go, controller/service.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/ipfamily/ipfamily.go, internal/ipfamily/ipfamily_test.go, internal/layer2/announcer.go, internal/layer2/announcer_test.go, speaker/bgp_controller.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go, speaker/main.go
Refactor Metallb service controller to support dual stack, this PR is continuation of the effort started by 
PR #727 while trying to share most of the code between single stack and dual stack services, also it modifies to speaker code to return more than one address instead of one Loadbalancer IP.
- bring up kind dual-stack cluster 
- create metallb configmap
```
k -n metallb-system get configmap config -o yaml
apiVersion: v1
data:
config: |
peers:
- peer-address: fc00:f853:ccd:e793::5
peer-asn: 64512
my-asn: 64512
address-pools:
- name: dev-env-bgp
protocol: bgp
addresses:
- 192.168.10.0/24
- fc00:f853:0ccd:e799::/124
kind: ConfigMap
```
- create dual-stack svc
```
k create -f dev-env/testsvc_dualstack.yaml 
```
- loadbalancer svc
```
k get svc nginx 
NAME    TYPE           CLUSTER-IP …
```
=> Refactor Metallb svc controller and speaker to support dual-stack

e2etest/bgp_test.go, e2etest/layer2_test.go
Create two address pools and request a specific address pool for each Loadbalancer service. Validate functionality.
Create two peers and validate each FRR container is paired with the cluster nodes.
=> Add E2E configuration changes tests

.circleci/config.yml
MetalLB CI is currently pinned to install Kind v0.10.0, a release based on Kubernetes v1.20.2. Bumping to v0.11.1 (latest released as of today) based on Kubernetes v1.21.1.
=> Bump kind to v0.11.1

e2etest/pkg/frr/container/container.go, manifests/metallb-frr.yaml, tasks.py
There is a rate limit in dockerhub. To avoid it we should pull the FRR image from quay.io.
=> Update FRR image URL to quay.io

website/content/community/maintainers.md
Try number two to do this: https://github.com/metallb/metallb/pull/1082
I consider the previous LGTM still valid for this PR so I'll merge this ASAP, let me know otherwise and I can change this in the future and fix what you think in a follow-up PR.
It is a simple step documentation, that hopefully now renders fine with the hugo version used by the server.
=> website: Documents new steps when adding maintainers

e2etest/layer2_test.go
Currently the first BeforeEach creates a generic addresspool
that is sometimes overridden by the test. We should have
all tests declare the addresspools for themselves,
with a clear name that ties it to them.
=> Specify the addresspool in each L2 test

e2etest/bgp_test.go, e2etest/pkg/frr/config/config.go
Enable richer bgpd logs and dump the content of /etc/frr/daemons on failure.
=> Enable bgpd debug on test failure

e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go
This is probably the cause of the flakes we are experiencing in CI, as discussed with @ton31337 on slack.
Reference FRR issue https://github.com/FRRouting/frr/issues/10142
=> Set RouterID in the external containers

e2etest/bgp_test.go, frr-metrics/collector/bfd.go, frr-metrics/collector/bfd_test.go, frr-metrics/collector/bgp.go, frr-metrics/collector/vtysh.go, frr-metrics/exporter.go
The new BFD collector creates BFD metrics based on BFD peers counters.
Adding unit tests to verify BFD metrics collector functionality and extending the BFD E2E test to check BFD metrics.
=> Add BFD metrics collector 

e2etest/bgp_test.go
When running hostnetworked, frr on metallb side squashes the ip and
configures one single neighbor. Here we add one single container in case
tests are running in hostnetwork mode.
=> Run one single external container in case of hostnetwork

manifests/metallb-frr.yaml, manifests/metallb.yaml
As in the Helm chart, we use the Prometheus endpoint for controller liveness and readiness probes on the k8s manifest.
The liveness and readiness probes parameters are aligned to the Helm chart defaults.
Fixed #952
=> Add controller liveness and readiness probe

e2etest/bgp_test.go, e2etest/pkg/frr/config/config.go, internal/bgp/frr/config.go, internal/bgp/frr/testdata/TestBFDWithSession.golden, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
BGP routes must only be published. We should not accept incoming routes, as FRR is host networked and that would result in unwanted routes at host level of the cluster.
We use prefix-list to block the routes.
=> FRR: block incoming routes

e2etest/pkg/frr/config/config.go
Enable BFD debug peer on the FRR test containers to help debugging BFD peering issues
=> Enable BFD debug command on the e2e test containers

e2etest/bgp_test.go, e2etest/layer2_test.go, e2etest/pkg/config/update.go
We should use the configMapName variable instead of hardcoding the configmap name, so we will be able to run the E2E tests
using different MetalLB configmap names.
=> E2Etests fix: Use configMapName variable in configmap updater

frr-metrics/collector/bfd.go
BFD peer has 4 states: up, down, init, or failing.
If we only check the "down" status we state that the session is up while it can be init or failing.
=> BFD metrics: Fix session up metrics determination method

internal/bgp/frr/config.go, internal/bgp/frr/testdata/TestBFDProfileAllDefault.golden, internal/bgp/frr/testdata/TestBFDProfileCornerCases.golden, internal/bgp/frr/testdata/TestBFDProfileNoSessions.golden, internal/bgp/frr/testdata/TestBFDWithSession.golden, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestSingleSessionClose.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
The native implementation could use the default route to peer with
routers outside its network that couldn't be reached otherwise.
We should enable it in FRR as well to support peering with these routers.
https://docs.frrouting.org/en/latest/zebra.html#clicmd-ip-nht-resolve-via-default
=> FRR: Allow nexthop tracking to resolve via the default route

e2etest/bgp_test.go
currently the function peersForContainers in e2etest/bgp_test.go
ignores the argument containers and loops through frrContainers
this commit fixes it.
=> Fix peersForContainers function

e2etest/e2etest_suite_test.go
If we are running in operator mode the MetalLB configmap can be found in the cluster because the operator is managing it
and not the tests. In such case BeforeSuite shouldn't fail.
This change allows us running the E2E tests more than once in a cluster where MetalLB was deploying through operator.
With the previous validation method a second run of the tests was failing as the configmap exist.
=> E2E tests: Fix MetalLB configmap exist check in BeforeSuite

e2etest/bgp_test.go, e2etest/e2etest_suite_test.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go, tasks.py
Instead of creating and destroying the containers after each run, we create them only once and we keep them for all the tests.
This has several benefits:
- Reduce the test run time since we don't have to pay the container
creation each time
- The test suite will clean the container even when we block the test
execution
- This is likely to reduce / remove the flake that happens at container
start time
=> E2E: create the external containers only once

e2etest/bgp_test.go, e2etest/pkg/frr/container/container.go, e2etest/pkg/frr/daemons.go
Some tests fails for not having FRR loading the right configuration right after starting the container. Here we check for the daemons to be ready before giving it away.
=> E2E: wait for daemons to be available in external frrs

e2etest/pkg/config/update.go, go.mod, go.sum
https://github.com/metallb/metallb-operator/commit/5703e8dc4cae2a58bb40c69ed2440eafa845392e
changed BGPPeer api to use metav1.Duration instead of time.Duration.
This change should also be reflected here.
=> E2E: Update operator BGPPeer

e2etest/pkg/frr/container/container.go
A leftover that sneaked through reviews.
=> Remove unwanted debug log

.circleci/config.yml, .github/workflows/ci.yaml, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/container/container.go, tasks.py
Modify circle config.yaml to allow core file generation at /tmp folder and modify rawDump to check if there is any core is created 
Unit-test
```
bash-5.1# pkill -SIGSEGV bgpd
bash-5.1# ls -l /tmp/
total 5832
-rw-------    1 root     frr      107610112 Dec  7 01:31 core-bgpd.74.f874d0073cc1.1638840711
gdb -q -n -ex bt /usr/lib/frr/bgpd /tmp/core-bgpd.74.f874d0073cc1.1638840711
[New LWP 74]
[New LWP 77]
[New LWP 75]
[New LWP 76]
Missing separate debuginfo for the main executable file
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/c2/5fc6b15e6584ebfa378da6575ef7ea76a495d3
Core was generated by `/usr/lib/frr/bgpd -d -F traditional -A 127.0.0.1'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6f6422ef98 in ?? ()
[Current thread is 1 (LWP 74)]
#0 …
```
=> Add support to generate bgpd corefile for CI

.circleci/config.yml
After the successful migration to gh actions, we can remove the e2e lanes from circleci, leaving only the promotion jobs.
=> Remove e2e jobs from circleci

.github/workflows/ci.yaml
Now that we have also the deployment as another dimension for lanes, we need to embed it into the names of the logs otherwise they get overwritten.
=> CI: extend the kind logs with the deployment type

e2etest/pkg/frr/bgp.go
Running `ls` and piping to `head -n 1` will always(?)
result in a 0 exit code.
Refactoring to check if crashlogs exist and iterating
over them one by one.
=> E2E: Fix crashinfo dump

e2etest/bgp_test.go, e2etest/pkg/frr/bgp.go
This change will enable all dumping steps
to finish before returning from the func,
which will give us more logs in case some
step fails before the others.
=> E2E: Combine FRR dump errors

e2etest/bgp_test.go, internal/bgp/frr/config.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestBFDWithSession.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleSession.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
If we have a peer but no advertisements, the deny route map is not added and a peer may inject routes from outside.
=> FRR config: deny is added only when announcing an address

internal/config/config.go, internal/config/config_test.go
If we specify addresses in a pool by range (and not by cidr), the check
that the lenght of the cidr is bigger than the aggregation lenght is
performed against all the possible cidrs that range translates to, and
it is misleading. The check makes sense when we declare a cidr, because
we know we won that whole cidr, but in the other case we may be using a
subset of a cidr for other reasons, and the check here leads to false
negatives.
A scenario like the one in the test that is being added should not fail:
3.3.3.2-3.3.3.254 with aggregation length 26
=> Check aggregation length against the wider cidr generated from range

e2etest/pkg/config/update.go, go.mod, go.sum
Now that https://github.com/metallb/metallb-operator/pull/136 added
the EBGPMultiHop field to BGPPeer we should use it here.
Without this --use-operator can't work.
=> E2E: Update operatorUpdater to use EBGPMultiHop

tasks.py
When the services ipv4 / v6 ranges are injected from outside, we don't
have to reserve a specific ip to the containers, so we must not set the
"ips-for-containers*" parmaeters and let docker assign custom ips.
=> E2E: provide empty ips for the containers when the ranges are passed

website/content/configuration/weave.md
`NO_MASQ_LOCAL` is enabled by default (https://github.com/weaveworks/weave/pull/3756) as of weave 2.7, so update the docs to reflect this change
=> Update issue page with Weave NO_MASQ_LOCAL default

e2etest/bgp_test.go
Deleting the multi-hop-net makes sense only if we created
it earlier, meaning when we're using a network other than
host for our containers.
=> E2E: Delete multi-hop-net only when host-network isn't used

tasks.py
Some CI runs failed because they hit the 40m limit (especially dual stack tests), here we make the timeout longer.
=> Make the tests timeout longer

e2etest/pkg/config/parse.go, e2etest/pkg/config/update.go, e2etest/pkg/metallb/config.go, internal/config/validate.go, internal/config/validate_test.go, speaker/main.go
Currently FRR does not allow to do two different things:
- Having different myAsns for different bgp peers
- Having different routerids for different peers
The result is misleading, because the rendered configuration will consume only the last added myasn (or routerid) of the list, resulting in a different behaviour from what the user is expecting from the api. Here, we reject the configuration in such cases, and we remove the routerid setting from the tests.
=> FRR mode: fail in unsupported scenarios

e2etest/bgptests/bgp.go, e2etest/pkg/config/parse.go, e2etest/pkg/service/create.go
Fixes #1047 
Adding a single test to inspect a full BFD configuration. Multiple configurations tests are already in place in unit tests (see internal/bgb/frr package).
~~The test also connect to a BGP peer and publish a serivce, that it may be redundant.~~
Update: test checks frr configuration is correct without connecting to peers, as it result in a faster test run.
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
=> E2E: Verify configuration in FRR containers

manifests/metallb-frr.yaml, manifests/metallb.yaml
Remove namespace from PodSecurityPolicy definitions
PSP are cluster resources and the _namespace_ definition is ignored by the API anyway.
=> Remove namespace from PodSecurityPolicy definitions

controller/controller_test.go, controller/main.go
When edit configmap for existing service, the config was rejected and
not re-enqueued for reprocess when the service update takes place,
causing the service to stay in pending state till it get deleted
by k8s.
=> Controller: enqueue the failed configmap till services update

controller/service.go
The controller can panic if a user updated a service by specifying
a different IP than the one currently assigned and changing another
field that causes the controller to clear the service's state.
For example, updating the address pool of a service and specifying
spec.loadBalancerIP from the new address pool results in:
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
main.(*controller).convergeBalancer(0xc0001205a0, {0x15cf500, 0xc0001bbc20}, {0xc0002b8730, 0xf}, 0xc000132c80)
/home/obraunsh/projects/metallb/controller/service.go:118 +0x2306
```
=> Controller: fix panic in convergeBalancer

e2etest/bgptests/bgp.go, e2etest/bgptests/validate.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go, e2etest/pkg/frr/validation.go, e2etest/pkg/k8s/nodes.go, e2etest/pkg/metallb/config.go, e2etest/pkg/routes/routes.go
During the dual stack implementation, an "ipfamily" type was introduced.
E2e tests kept using the strings, here we align them to use the type,
enforcing the values.
=> Tests: Use the ipfamily type instead of strings

internal/k8s/k8s.go
After doing a successful sync of an item it should be removed from the work queue.
Doing this mainly for deleted services. So far, after deleting a service the service item was left in the queue
(because "SyncStateSuccess" is not doing anything) and once created again (for example in the E2E tests), each update
was taking longer and longer time based on the exponential rate limiter.
=> Speaker: Fix: Remove items from work queue after sync 

e2etest/bgptests/bgp.go, e2etest/pkg/config/parse.go, e2etest/pkg/config/update.go, e2etest/pkg/metallb/config.go, internal/bgp/frr/parse.go, internal/bgp/frr/parse_test.go, internal/config/validate.go, internal/config/validate_test.go
To overcome the current frr limitation, instead of failing if
routerid is set, we enable a more permissive logic to allow
setting routerid only if all the routerids are equal.
=> FRR mode: allow setting routerid if all equal

e2etest/e2etest_suite_test.go
Calling framework.NewDefaultFramework() inside BeforeSuite results in:
```
You may only call BeforeEach from within a Describe, Context or When
```
Changing that to get the ClientConfig in a different way.
=> E2E: Fix operator mode

e2etest/bgptests/bgp.go
The e2e tests work in configmap mode, but do not in operatormode because uppercase is not allowed in CRs names.
=> E2E: make bfd profile name lowercase

e2etest/bgptests/bgp.go, e2etest/pkg/frr/bgp.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestBFDWithSession.golden, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden, internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden, internal/bgp/frr/testdata/TestSingleIBGPSession.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden, internal/ipfamily/ipfamily.go
The current communities / local pref handling suffers of two issues:
- the route-map is added always with the same id, basically overriding
all the communities and leaving the last one as the only available
- the route-map is not filtered per prefix. MetalLB api bounds the community and the local preference to the address pool, which means that they must be a property of the announcement.
Here we make a change in the template so that every route-map entry with the same name gets a different id, with the extra complication that we can't bind a route-map entry to a given ip, so it's necessary to collect the ips related to a community (or to a local pref) under a prefix-list.
E2E tests are modified to validate that only the ips coming from the right pool are advertised with the given …
=> FRR: fix communities and local preferences

e2etest/pkg/config/update.go
1. The BgpAdvertisements length should be zero to avoid empty elements in the slice.
2. The Communities length should be set before copying the slice as copy function set's the number of copied
elements to the minimum of len(dst) and len(src) which is zero in this case.
=> E2E tests: Fix operator mode AddressPool conversion function

.github/workflows/ci.yaml, e2etest/pkg/metallb/metallb.go, manifests/metallb-frr.yaml, manifests/metallb.yaml, manifests/prometheus-operator.yaml
If users are using the manifests, upgrading will not work because of the
change of the label selector of the daemonset / deployment.
Here we revert and adjust the value used by the tests, and override the
selector in tests because helm uses the app.kubernetes.io/component
version.
=> Revert the speaker and controller selector to the old version

e2etest/bgptests/bgp.go, e2etest/pkg/frr/bgp.go, internal/bgp/frr/config.go, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
When we have both communities and localpref advertisement, the community advertisement is skipped because frr stops at the first match.
Here we add on-match next to let it continue.
Also, refactoring advertisement e2e so we can have mixed scenarios.
=> FRR route-rules: add on-match next

controller/controller_test.go, controller/service.go, e2etest/bgptests/bgp.go, e2etest/bgptests/validate.go, e2etest/pkg/service/tweak.go, website/content/usage/_index.md
This PR aims to fix #1155 issue by adding new custom annotation field `metallb.universe.tf/loadBalancerIPs `which can be used to request specific IPs (single and dual stack). For now this would coexist with `svc.Spec.LoadBalancerIP `field. when both fieds are specified, then annotation field takes higher precedence than spec field.
=> Controller: custom annotation for pinning ips (single and dual stack)

controller/main.go, e2etest/pkg/frr/config/config.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_bfd_test.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestLoggingConfiguration.golden, internal/bgp/frr/testdata/TestLoggingConfigurationDebug.golden, internal/bgp/frr/testdata/TestLoggingConfigurationOverrideByEnvironmentVar.golden, internal/logging/logging.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/main.go, website/content/installation/_index.md
Hi,
To allow debugging of FRR speaker container, it would be useful to forward the speaker `--log-level` parameter to the FRR configuration. Not sure about the design in forwarding the logLevel parameters from `main()` to `frr.NewSessionManager(...)`, feedback is wellcome.
It would also useful to add lines like these to the configuration, in order to debug specific protocols:
```
debug zebra events
debug zebra nht
debug zebra kernel
debug zebra rib
debug zebra nexthop
debug bgp bfd
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd distributed
debug bfd network
debug bfd peer
debug bfd zebra
```
To achieve that, the following options come to my mind:
a. Add all that configuration if `--log-level` is set do debug, or if condition like …
=> Forward speaker log level to FRR configuration in order to improve debuggability

e2etest/bgptests/bgp.go
As explained [here](https://github.com/metallb/metallb/issues/1196#issuecomment-1026076150), the
`configure peers one by one and validate FRR paired with nodes` relies on BGP FRR peers to be reachable
by speaker nodes but the default configuration does not allow ipv6 traffic to be forwarded to the `multi-hop-net`.
Not sure this fix is clean enough or it's worth to refactor tests.
Fixed #1196
=> E2E: Avoid BGP:FRR spec flakiness

internal/config/config.go, internal/config/config_test.go
When configuring an addressPool with two same BGPAdvertisements, an error should be produced.
=> AddressPool validation: Add BGPAdvertisement validation to avoid duplication

internal/bgp/frr/frr_test.go
Hi,
I discovered a flaky unit test caused by the [asynchronous nature of the debouncer](https://github.com/metallb/metallb/blob/46675f03d788549897ff59c6b3b268c162a394d0/internal/bgp/frr/config.go#L328).
Here the symptom:
https://github.com/metallb/metallb/runs/4920413290?check_suite_focus=true
The check is done against an intermediate configuration file generated during the test, as `TestTwoAdvertisementsTwoSessions` triggers the configuration render twice.
This PR make the assertion to be repeated using a poll interval, so if spurious config file should be discarder.
Please, let me know if there is a better way to work around this edge case.
=> Repeat check for frr config file

.github/workflows/ci.yaml, e2etest/l2tests/l2.go
This makes e2e also run in operator mode to ensure MetalLB CI setup is
working fine when its deployed via its operator.
Fixes #1185
=> E2E: Run e2e also in operator mode

website/content/release-notes/_index.md
Before releasing, we bump the list of contributors again to include all
the people who contributed.
=> Release notes: update the list of contributors

charts/metallb/values.yaml, website/content/release-notes/_index.md
As the FRR mode is still experimental we set the helm chart default to disable FRR (can be optionally enabled).
Fixing issue https://github.com/metallb/metallb/issues/1221.
=> Helm chart: disable FRR mode by default

.github/workflows/cancel.yaml, .github/workflows/ci.yaml
When overriding a PR, previous jobs still run, and eventually filling the jobs available. Since the PR was overridden, there is no point in waiting them.
Here we use https://github.com/marketplace/actions/cancel-workflow-action to cancel them.
=> Cancel previous jobs when overriding a PR

README.md
This PR is quite simple:
* It fixes my email (kinvolk.com is not a valid domain, it is kinvolk.io!)
* It changes the advice to mail all of the maintainers instead (more reasons in the commit, but it seems just simpler and in case someone is AFK).
=> Fix my email in the README

tasks.py
When running dev-env, force debug logs in speaker and controller to ease the debug.
=> Dev-env: force debug logs in the pods

controller/controller_test.go, controller/service.go, internal/ipfamily/ipfamily.go
K8s versions prior to 1.20 do not have ClusterIPs set, so we fallback to clusterip (singular) to determine the ip family.
Tested locally with 
`inv dev-env --node-img=kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729` as the CI lanes are running against 1.21.
=> Fallback to clusterip to determine the service ipfamily

internal/bgp/bgp.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/native/messages.go, internal/bgp/native/native.go, internal/bgp/native/native_test.go, speaker/bgp_controller_test.go
The NextHop field is not used anymore, and it's misleading keeping it in the code. Here we remove it from the codebase and from the tests.
=> Remove NextHop from advertisements

website/content/community/maintainers.md
This commit adds documentation for the steps we currently know how to
do them and mentions other steps that are needed but we haven't check
the specific steps to do them.
Once we go doing the other steps, we will document them here. We just
add them so we have an exhaustive list of all the things to do and don't
forget about them.
=> Website: Document more steps for adding maintainers

.github/dependabot.yml
Adds dependabot to start checking Go dependencies.
resolves #1262
=> Add dependabot file to track go deps

e2etest/bgptests/bgp.go
When a test fails, trying to dump the frr information in native mode will result in an error. Here we check the len of containers and skip if there's only one container, assuming MetalLB is running in legacy mode.
=> E2E: dump frr containers in pods only if running in frr mode

tasks.py, website/content/installation/_index.md
Follow up of https://github.com/metallb/metallb/pull/1282
- The kustomize instructions are fixed and pinned to a specific release.
- The release task also bumps the all in one manifests
- We split the bump action in a separate function, so it's easier to check if changes in the bumping logic works
=> Adjust kustomize release / docs

controller/controller_test.go, controller/main.go
SetPools might be called with no pools,
e.g. when a user deletes the last ipaddresspool,
This commit fixes the if statement, as it's supposed  to
check if the pools parameter is nil, not if it's empty.
Added the check if pools is not empty before
calling c.ips.SetPools(pools)
And removed a test assertion that expects calling SetPools
with empty Pools to return SyncStateErrorNoRetry.
fix #1330
=> Fix SetPools function

website/content/usage/_index.md
@fedepaol I removed the below lines from _index.md, to resolve issue 1247. Please review.
"Note that in case of dual stack services, it is not possible to use spec.loadBalancerIP as it does not allow to request for multiple IPs.
This problem will be solved by using a custom service annotation in one of the next releases."
that weren't first discussed and …
=> Updated _index.md to resolve issue 1247

e2etest/bgptests/bgp.go, e2etest/pkg/service/create.go
We have a test that validate overlapping ips in l2, but we want to ensure it works also with bgp.
=> E2E: add a test that checks overlapping ip services in bgp

internal/k8s/controllers/endpoints.go, internal/k8s/controllers/service_controller.go, internal/k8s/epslices/endpoint_slices.go, internal/k8s/k8s.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go
=> Update code to use k8s.io/api/discovery/v1 instead of v1beta1

api/v1beta1/bgpadvertisement_types.go, api/v1beta1/l2advertisement_types.go, charts/metallb/templates/crds.yaml, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_l2advertisements.yaml, config/manifests/metallb-frr-with-webhooks.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-with-webhooks.yaml, config/manifests/metallb-native.yaml, e2etest/bgptests/bgp.go, internal/config/config.go, internal/config/config_test.go
This adds label selector option for l2 and bgp advertisement to
select ip pools which would get advertised to peers via this
advertisement configuration settings.
=> Add label selector to l2 and bgp advertisement

.github/workflows/ci.yaml, charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, config/frr/speaker-patch.yaml, config/manifests/metallb-frr-with-webhooks.yaml, config/manifests/metallb-frr.yaml, e2etest/bgptests/bgp.go
re-enabling the E2E lane that ensures MetalLB is working fine when its deployed via operator.
=> CI: Re-enable E2E operator lane

e2etest/bgptests/bgp.go, e2etest/bgptests/setup.go, e2etest/l2tests/l2.go, e2etest/pkg/service/validate.go
We currently support the announcement of the same ip to both l2 and bgp, so here we add a test for that. It's part of the BGP section because we need the infrastructure provided by the BGP context.
=> E2e: add a test that validates the announcement on l2 and bgp

e2etest/e2etest_suite_test.go
All the tests clean before running. This means, the last test leaves the
cluster dirty.
=> E2E: clean the crds after running the suite

internal/logging/logging.go
Currently, the logger is always referencing "level.go:63" as the caller.
Also, it is printing the nanosecond with each timestamp
making the logs noisy.
This commit fixes those issues.
fix #1324
Before:
```
{"caller":"level.go:63","controller":"ConfigReconciler","level":"info","start reconcile":"/kind-worker2","ts":"2022-05-01T15:19:34.80207407Z"}
{"caller":"level.go:63","controller":"ServiceReconciler - reprocessAll","level":"info","start reconcile":"metallbreload/reload","ts":"2022-05-01T15:19:34.802084883Z"}
{"caller":"level.go:63","controller":"ConfigReconciler","event":"force service reload","level":"info","ts":"2022-05-01T15:19:34.802192555Z"}
{"caller":"level.go:63","controller":"ConfigReconciler","event":"config reloaded","level":"info","ts":"2022-05-01T15:19:34.802207787Z"} …
```
=> Change logger output

api/v1alpha1/addresspool_types.go, api/v1beta1/addresspool_types.go, api/v1beta1/bgpadvertisement_types.go, api/v1beta1/bgppeer_types.go, api/v1beta1/l2advertisement_types.go, api/v1beta2/bgppeer_types.go
The yaml names are a legacy of the initial implementation of the
operator, which was leveraging them to render the configmap. They are
not needed anymore.
=> API: remove yaml marshalling names

internal/bgp/frr/config.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestSingleIPv6EBGPSessionOneHop.golden, internal/bgp/frr/testdata/TestSingleIPv6IBGPSession.golden, internal/bgp/frr/testdata/TestTwoIPv6Sessions.golden
There is an issue with how MHT works for IPv6 neighbors
specifically if DHCPv6 was used to assign interfaces IP
because of this issue eBGP directly connected sessions
won't get to establish state.
using disable directly connected check mitigate this
issue for the time being till frr has fix.
for more details about this issue pls refer to
https://github.com/FRRouting/frr/issues/11185
=> Disable directly connected check for IPv6 eBGP sessions by default

.github/workflows/ci.yaml, speaker/main.go
This commit fixes service announced metric to be deleted from
prometheus when corresponding load balancer type service
is removed.
Fixes #1342 
=> Update metrics when service is deleted

api/v1beta1/addresspool_types.go, api/v1beta1/ipaddresspool_types.go, charts/metallb/templates/crds.yaml, config/crd/bases/metallb.io_addresspools.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/manifests/metallb-frr-with-webhooks.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-with-webhooks.yaml, config/manifests/metallb-native.yaml, e2etest/pkg/config/parse.go, e2etest/pkg/config/validate.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/config/config.go, internal/config/config_test.go, website/content/apis/_index.md
When defining the first version of the CRDs, it was decided not to
expose this flag.
If .0 / .255 ips are problematic, users can define custom ranges to skip
them. Given this is the first version of the api, we are removing the
field in order to propose a slimmer api surface, with the possibility of
readding it later on.
Link to the discussion: https://github.com/metallb/metallb-operator/pull/17#discussion_r652824338
=> Remove the avoidBuggyIps field from the api

charts/metallb/values.yaml, config/frr/speaker-patch.yaml, config/manifests/metallb-frr-with-webhooks.yaml, config/manifests/metallb-frr.yaml, e2etest/pkg/frr/container/container.go, tasks.py
Moving back to dockerhub since it's the official FRR image, plus it supports multi - architecture.
=> FRR: restore the image from dockerhub

.github/workflows/ci.yaml, api/v1beta1/bfdprofile_webhook.go, api/v1beta1/bfdprofile_webhook_test.go, api/v1beta1/bgpadvertisement_webhook_test.go, api/v1beta2/bgppeer_webhook.go, api/v1beta2/bgppeer_webhook_test.go, charts/metallb/templates/crds.yaml, charts/metallb/templates/rbac.yaml, charts/metallb/templates/webhooks.yaml, config/manifests/metallb-frr-with-webhooks.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-with-webhooks.yaml, config/manifests/metallb-native.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml, e2etest/backwardcompatible/patchfile, e2etest/webhookstests/webhooks.go, internal/k8s/k8s.go
This PR is adding a validation webhook to the BFDProfile CRD.
This webhook only validates a delete action, asserting that the deleted
profile is not being used by a BGPPeer. 
For "create" and "update" validation, the CRD handles it itself with limits values.
=> Add BFDProfile validation webhook

.github/workflows/ci.yaml, .github/workflows/composite/collectlogs/action.yaml, .github/workflows/composite/setup/action.yaml, charts/metallb/templates/speaker.yaml, config/controllers/speaker.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native.yaml, e2etest/bgptests/bgp.go, e2etest/bgptests/bgppeer_selector.go, e2etest/bgptests/node_selector.go, e2etest/l2tests/l2.go, e2etest/l2tests/node_selector.go, go.mod
- Refactor the shared steps in a composite action we can reuse
- Bump the kind version used by CI (and the version of the cluster we test against)
- Add a lane to test against the oldest supported k8s version (1.22)
=> CI: use composite action to collect the setup step

.github/workflows/ci.yaml, charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, controller/main.go, e2etest/l2tests/loadbalancer_class.go, e2etest/pkg/service/tweak.go, internal/k8s/controllers/service_controller.go, internal/k8s/controllers/service_controller_reload.go, internal/k8s/controllers/service_controller_test.go, internal/k8s/k8s.go, speaker/main.go, website/content/installation/_index.md
Loadbalancer class enable different loadbalancers to co-exist. We add a parameter to the speaker and the controller to process only the services consistent with the loadbalancer class provided to metallb.
Fixes https://github.com/metallb/metallb/issues/685 and https://github.com/metallb/metallb/issues/996
=> Add support for LoadBalancerClass

.github/workflows/ci.yaml
Aligning the metallb operator used in CI to the latest version so we can consume the latest webhook changes.
=> CI: Bump the operator version

configmaptocrs/Dockerfile, controller/Dockerfile, speaker/Dockerfile
Small MR to add OCI image annotations to speaker and controller images.
Fixes #1392 
Signed-off-by: Joshua Carnes <56089764+jtcarnes@users.noreply.github.com>
=> Add OCI image annotations

.github/workflows/ci.yaml, .github/workflows/composite/setup/action.yaml, .github/workflows/publish.yaml, configmaptocrs/Dockerfile, controller/Dockerfile, mirror-server/Dockerfile, speaker/Dockerfile, tasks.py
This MR changes the build process for metallb to build inside a docker container instead of building outside and copying in. It further refactors much of the CI to better build images inside containers and leverage github actions instead of custom scripting.
Fixes #1392 #1408 #1413
=> Build in container and update CI

.github/workflows/publish.yaml
Fixes release CI's docker metadata action to properly generate tags
instead of failing.
=> Fix docker metadata action

.github/workflows/publish.yaml
We need to checkout otherwise the dockerfiles won't be available.
Moreover, we set push to true to push the images.
=> Publish: checkout before publishing

charts/metallb/README.md, charts/metallb/templates/podmonitor.yaml, charts/metallb/templates/prometheusrules.yaml, charts/metallb/values.yaml, website/content/release-notes/_index.md
My particular use case is adding the following annotation:
```
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
=> Helm: Add optional annotations for podMonitors and prometheusRules

internal/k8s/k8s.go
metallbv1alpha1 api is missing.
=> Add metallbv1alpha1 api to runtime scheme

go.mod, go.sum, internal/logging/logging.go
We need to set a controller-runtime logger to print all the logs created by it. For exmaple:
https://github.com/metallb/metallb/blob/359e54d75df4c930125535cd9b4ce4dff1c45ee6/internal/k8s/k8s.go#L60
Log is the base logger used by controller-runtime. It delegates to another logr.Logger that must be set by SetLogger to get any actual logging.
=> Add controller-runtime logger

internal/k8s/k8s.go
Disable the metrics endpoint in controller-runtime manager,
to allow start up on hosts that already use port 8080.
Fixed #1432
=> Disable metrics endpoint in controller-runtime

e2etest/bgptests/bgp.go, e2etest/bgptests/bgp_multiprotocol.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go, e2etest/pkg/frr/validation.go, e2etest/pkg/service/tweak.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/parse.go, internal/bgp/frr/testdata/TestBFDWithSession.golden, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNonExistingPeer.golden, internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden, internal/bgp/frr/testdata/TestSingleAdvertisementWithPeerSelector.golden, internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden, internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden, internal/bgp/frr/testdata/TestSingleIBGPSession.golden, internal/bgp/frr/testdata/TestSingleIPv6EBGPSessionOneHop.golden, internal/bgp/frr/testdata/TestSingleIPv6IBGPSession.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessionsOneWithPeerSelector.golden, internal/bgp/frr/testdata/TestTwoIPv6Sessions.golden, internal/bgp/frr/testdata/TestTwoSessions.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden, internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden, website/content/concepts/bgp.md, website/content/release-notes/_index.md
Changing the way we render the config to accommodate MP-BGP.
We advertise the ips regardless of the ip family of the session established with the neighbor, plus we add e2e tests for that.
Fixes https://github.com/metallb/metallb/issues/1402
=> Restore MP-BGP

.github/workflows/ci.yaml
We normally align the operator to metallb changes, and this will avoid
the extra jump of bumping back the operator on metallb ci due to a
change in metallb itself.
=> Always use the main branch of the operator for CI

website/content/installation/network-addons.md
Hi folks ! Me and @vrabbi were just talking about this - and i did some experiments on kind, and metallb seems quite happy.  Scott also has many metallb L3 deployments he's run on VMWare tanzu, so it's safe to update the list of CNIs.
=> Adding Antrea to the list of supported CNIs

api/v1beta1/l2advertisement_webhook.go, api/v1beta1/l2advertisement_webhook_test.go, api/v1beta1/mock_validator_test.go, charts/metallb/templates/webhooks.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native.yaml, config/webhook/manifests.yaml, internal/k8s/k8s.go
The validation webook is currently missing for l2 adv
object, this commit ensures such validating webhook
implmented for it.
=> Add validation webhook for L2Advertisement

e2etest/bgptests/bgp.go, e2etest/l2tests/l2.go, e2etest/pkg/metrics/metrics.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/node_controller.go, internal/k8s/controllers/pool_controller.go, internal/k8s/controllers/service_controller.go, internal/k8s/controllers/stats.go
In migrating to CRDs, we omitted filling the metrics related to k8s
events. Here we re introduce them.
=> Restore the k8s events metrics

internal/bgp/frr/config.go, internal/bgp/frr/debounce_test.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go
Making the interaction with FRR more robust introducing retries after failures in both the call of the reloader (if the pid is not there yet) and if we find that the interaction between the reloader and the container fails.
Fixes https://github.com/metallb/metallb/issues/1462
=> FRR configuration retries

tasks.py
When we splitted the release in release + bumprelease, we changed the
semantic of bumprelease which accepts a string and not a semver object.
This is done to be able to test the bumprelease function without having
to do the whole release process. Here, we fix it to provide the function
the version string coming from outside.
=> Tasks: fix the release command

.github/workflows/publish.yaml
During the latest release, the job did not trigger. Using the same as
the helm chart which was triggered.
=> Publish job: change the branch / tag selector

.github/workflows/publish.yaml
Images were being published without the leading v on their version.
The change should now properly append the v onto the tag version.
Fixes #1474
=> Change Image tagging to use old style

website/content/configuration/_index.md
The lack of namespace causes the error:
```
✗ L2Advertisement/local-network-ips namespace not specified, error: the server could not find the requested resource (patch l2advertisements.metallb.io local-network-ips)
```
=> [website] Add namespaces for {L2,BGP}Advertisement

charts/metallb/templates/deprecated_configInline.yaml
This PR will prevent existing setups from destroying themselves, by raising an exception if `configInline` is defined.
```
philipp@ ~/metallb/charts/metallb (patch-2) $ helm template --namespace metallb-system metallb . --set configInline.bla.foo=hi
zsh: correct 'template' to 'templates' [nyae]? n
Error: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility
Use --debug flag to render out invalid YAML
philipp@ ~/metallb/charts/metallb (patch-2) $
```
=> feat: fail helm templating if configInline is defined

charts/metallb/templates/rbac.yaml, charts/metallb/templates/webhooks.yaml
The selector is only aiming at app.kubernetes.io/component, so if
there's another pod in the same namespace labeled controller, the
webhook service won't work (or it will work only if the service balances
the request to the real controller).
Also, give the controller the required permissions to watch communities.
=> Charts: add the selectorlabels to the webhook service and give controller permission to watch communities

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
This commit makes frr metrics port to be configurable
from helm chart values.
=> Helm: make frr metrics port configurable

internal/layer2/announcer.go, website/content/release-notes/_index.md
A regression introduced by
https://github.com/metallb/metallb/pull/1347, we were adding records to
the keepNDP map regardless of the fact that a v6 address was present on
the interface.
Here we enforce the if checking that the ip is not v4.
Fixes https://github.com/metallb/metallb/issues/1507
=> L2: add ndp responders when the address is v6 only

configmaptocrs/main.go, configmaptocrs/testdata/config.golden
We don't need to default it during the conversion, as if it's nil the config logic will fill it accordingly.
Moreover, deployments with the native bgp mode will fail.
The result is a CR with `keepaliveTime: 0s`, because of the 0 value of the struct. 
Nonethless, the webhook won't refuse the field and the loading logic will default the internal value to the right default if needed. 
This should address the second part of https://github.com/metallb/metallb/issues/1495, described here https://github.com/metallb/metallb/issues/1495#issuecomment-1179804400
=> Configmap converter: don't default keepalive time

tasks.py
The current replacement rules work only for main (and the frr one is
even bugged). Fixing to work also when moving from a minor version to
the next one.
=> Bumprelease: change the kustomize reference to be more greedy

charts/metallb/templates/controller.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
Another change required to align the operator deployment:
- setting the command for the two pods (in case the image used doesn't have a default entry point)
- setting the webhook mode (in the operator the webhook is deployed together with the operator, and in the controller the webhook is disabled)
=> Helm: setting the command for the controller and the speaker

internal/layer2/announcer.go, internal/layer2/announcer_test.go
In transitioning to dual stack we introduced an issue: if the ip was found, instead of returning the new code continued, grewing the a.ips[name] list on every service update.
=> L2 SetBalancer: return instead of continue if we find the ip

internal/k8s/k8s.go
v1beta1 is not being served anymore in 1.25, which will make metallb
unable to detect the availability of epslices.
Fixes https://github.com/metallb/metallb/issues/1578
=> Epslices detection: use discoveryv1 instead of v1beta1

e2etest/l2tests/l2.go, e2etest/pkg/udp/udp.go
Here we add a test validating metallb works with a service with both udp
and tcp associated.
=> E2ETests: add a test that check mixedprotocol services

frr-reloader/frr-reloader.sh, internal/bgp/frr/config.go, internal/bgp/frr/debounce_test.go, internal/bgp/frr/frr.go
In corner cases where we have a bouncing service, the number of updates requested to the reloader is higher than how fast the reloader is able to consume those requests. The requests are mutexed, so what happens is that we have a long (and growing) list of reloader child processes spun up by the sighup that we are not able to estinguish.
This consumes memory and may end up in having the speaker killed.
To fix this, we make the debounce timeout longer
Fixes https://github.com/metallb/metallb/issues/1581
=> Slower debounce time in FRR reloading

charts/metallb/templates/controller.yaml, config/controllers/controller.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml
To address issue https://github.com/metallb/metallb/issues/1610
=> Enhancement: adjust the readinessProbe to wait webhook-server to be ready

charts/metallb/README.md, charts/metallb/templates/podmonitor.yaml, charts/metallb/templates/servicemonitor.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, tasks.py
In general, Prometheus is able to watch the various resources needed such as serviceMonitor, So we don't need to explicitly create prometheus rbac resources in the matallb. Optional, You can also pass "--set prometheus.rbacPrometheus.enabled=true --set prometheus.rbacPrometheus.serviceAccount= --set prometheus.rbacPrometheus.namespace=<prometheus-operator-namespace" to create rbac resources for prometheus.
Signed-off-by:  cyclinder <qifeng.guo@daocloud.io>
=> Support optional creation of rbac resources for prometheus

e2etest/README.md, e2etest/bgptests/infra_setup.go, e2etest/e2etest_suite_test.go, e2etest/pkg/frr/container/container.go, tasks.py
This commit adds the option to run e2etests with existing containers, i.e. the tests don't create the external FRR containers, but use existing ones. see e2etest/README.md for more information.
Extra general code gardening:
* On e2etest_suite_test.go - Deleted redundant assertion.
* On container.go - Renamed function "Stop" to "Delete" to reflect better what it does.
* On container.go - Deleted redundant "todo" comment.
=> e2e: allow using external containers

website/content/_index.md
The reference is broken due to a typo, this is fixing it.
=> Website: fix the reference to the converter tool

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
Add option to set speaker sidecar resources in helm chart (for these containers, frr, reloader, and frr-metrics)
=> chart: add option to set speaker sidecar resources

charts/metallb/README.md, charts/metallb/templates/webhooks.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
This PR adds a new configuration option to the helm chart: `crds.validationFailurePolicy`. The value is injected into the validating webhook's `failurePolicy` field. Defaults to `Fail` (current behavior).
---
Closes https://github.com/metallb/metallb/issues/1598
=> configurable failurePolicy for validating webhooks

website/content/_index.md, website/content/concepts/bgp.md, website/content/configuration/_index.md, website/content/installation/_index.md, website/content/usage/_index.md
FRR is now be used by multiple users (and in OpenShift). Given that in long term we want it to be the BGP backend, it makes sense to remove the "experimental" wording that might intimidate some users.
=> Docs: remove the experimental wording around FRR

.github/workflows/ci.yaml
We must ensure the operator is running and can serve the webhook before applying the metallb resource.
=> CI: wait after deploying the operator

api/v1beta1/bfdprofile_types.go, api/v1beta1/bgpadvertisement_types.go, api/v1beta1/bgppeer_types.go, api/v1beta1/ipaddresspool_types.go, api/v1beta1/l2advertisement_types.go, api/v1beta2/bgppeer_types.go, config/crd/bases/metallb.io_bfdprofiles.yaml, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/crd/bases/metallb.io_l2advertisements.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml
This commit adds `+kubebuilder:printcolumn` markers to CRD structs so the generated CRDs are extended with `additionalPrinterColumns` properties.
---
Closes: https://github.com/metallb/metallb/issues/1459
=> CRDs: additionalPrinterColumns configuration

charts/metallb/templates/controller.yaml, config/controllers/controller.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, internal/k8s/k8s.go, internal/k8s/webhook.go
Fixes https://github.com/metallb/metallb/issues/1644
Revert the change of readiness probe, and change the webhook to start the metrics endpoint only after the webhooks are patched properly and thus able to serve.
=> Start the metrics after the webhook is ready

charts/metallb/templates/servicemonitor.yaml
This PR fixes the positioning of relabelings and metricRelabelings on the `ServiceMonitor`.
Resolves #1593
=> Fix servicemonitor relabelings

website/content/release-notes/_index.md
Doing a new release to fix the distracting error message in logs related to the webhook endpoint used as readiness check.
=> Release notes: prepare 0.13.7

controller/main.go, controller/service.go, e2etest/l2tests/assignment.go
When a service changes (i.e. changing the servicetype) and the IP is revoked, we reprocess the services so that the newly available ip is assigned.
Fixes https://github.com/metallb/metallb/issues/1586
=> Reprocess services when an ip is available because of a service change

e2etest/bgptests/bgp.go, frr-metrics/collector/bgp.go, frr-metrics/collector/bgp_test.go, internal/bgp/frr/parse.go, internal/bgp/frr/parse_test.go
This commit extends the number of metrics we collect about BGP sessions
using FRR.
The following additional metrics are extracted from the FRR's vtysh
"show bgp neighbors" command.
- OpensSent
- OpensReceived
- NotificationsSent
- UpdatesSent
- UpdatesReceived
- KeepalivesSent
- KeepalivesReceived
- RouteRefreshSent
- TotalSent
- TotalReceived
All of the metrics above are counters of different BGP messages and
they are collected per BGP neighbor.
Note:
The choice of the metric name: "updates_total_received"
was made to keep backward compatibility with the already existing `bgpstats.UpdatesSent.Name`
=> Extend FRR BGP Prometheus metrics collection

api/v1beta1/ipaddresspool_types.go, charts/metallb/charts/crds/templates/crds.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, website/content/apis/_index.md
This enhances IPAddressPool CRD as per this [proposal](https://github.com/metallb/metallb/blob/main/design/pool-configuration.md#using-a-given-ipaddresspool-only-for-a-subset-of-services-1) for allocating ip from a pool only to specific service(s) and/or namespace(s). It also provides an option for advertising ip only to selected BGP peers.
=> Enhance IPAddressPool CR for service allocation

design/vrf-announcement.md
Adding the design proposal of a feature we are requested by a few telco users: making it possible to announce a service via an interface wrapped in a VRF.
Note: this covers only the announcement part and not how the CNI handles the traffic coming to / from a VRF.
=> Add a design proposal for announcing a service via VRFs

controller/main.go, controller/service.go, e2etest/l2tests/l2.go
annotate a service with the pool used to provide its IP
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>
Fixed https://github.com/metallb/metallb/issues/1448
=> annotate a service with the pool used to provide its IP

website/content/prometheus-metrics/_index.md
Add a new page with tables describing the available metrics MetalLB collects.
(this includes the new metrics that PR #1657 adds)
fix #1344 
Preview:
=> Website: Add Prometheus metrics section

charts/metallb/Chart.yaml, charts/metallb/README.md
When I install metallb by chart, the output:
```
$ helm install metallb -nkube-system ./ --dry-run
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecationWarning" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, …
```
=> Fix chart of metalb  crd support version for k8s

configmaptocrs/conversion_test.go, configmaptocrs/main.go, controller/main.go, e2etest/pkg/frr/container/container.go, internal/bgp/frr/config.go, internal/bgp/frr/docker_test.go, internal/bgp/native/messages.go, internal/bgp/native/messages_test.go, internal/bgp/native/native.go, internal/layer2/announcer.go, speaker/main.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
We should clean all io/util package according the url: https://go.dev/doc/go1.16#ioutil
/kind cleanup
=> remove io/ioutil for advanced golang

frr-reloader/frr-reloader.sh, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/dump.go, internal/k8s/controllers/pool_controller.go
We expose the password in the logs in two places:
- when the speaker container dumps the configuration, because an error happened or because the log level is raised to debug
- in the reloader container, every time an frr configuration gets generated
Here, in both places we replace the password before logging.
=> Hide the bgp password from logs

internal/layer2/announcer.go, internal/layer2/ip_advertisement.go
If a responder fails to be set (i.e. ndp on a ipv4 only node), then the list of interfaces is not being built.
That results in l2 mode entirely not working. Here we make the mechanism a bit more robust by continuing on errors.
Fixes https://github.com/metallb/metallb/issues/1727
=> L2: avoid having one failure on responder disable l2

charts/metallb/templates/rbac.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, config/rbac/role.yaml, controller/controller_test.go, controller/main.go, controller/service.go, e2etest/l2tests/assignment.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/config/config.go, internal/config/config_test.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/config_controller_test.go, internal/k8s/controllers/pool_controller.go, internal/k8s/controllers/pool_controller_test.go, internal/k8s/listener.go, speaker/bgp_controller_test.go, speaker/layer2_controller_test.go, speaker/main.go, speaker/speaker_test.go
This changes ip allocation logic when ip pools are configured with namespace, service/namespace label selectors so that ip are allocated from desired pools based on its priority before it tries to allocate from other ip pools.
=> Implement ip pool selector logic for service

.github/workflows/ci.yaml, e2etest/README.md, e2etest/bgptests/infra_setup.go, e2etest/bgptests/validate.go, e2etest/e2etest_suite_test.go, e2etest/pkg/container/routes.go, e2etest/pkg/netdev/netdev.go, e2etest/pkg/routes/patch.go, tasks.py
Extending the set of containers with another two reacheabile via multihop through the interface in the vrf.
The multihop setup function is made generic so that can be applied to the containers in vrf too.
=> E2E VRF: validate multi hop via vrf

.github/workflows/ci.yaml, controller/service.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go
In case we want to have the cluster administrator enforce the multi tenancy configurability of metallb, we need to disable the option for users to pin to a specific pool.
Hence this enhances ip address pool crd to disable manual ip address pool selection when its ip addresses are requested through service metallb.universe.tf/loadBalancerIPs or metallb.universe.tf/address-pool annotation.
=> Disable manual ip address pool selection

e2etest/l2tests/assignment.go
If there is a service of type loadbalancer in the cluster we are testing against, it will steal the single ip we expect to be assigned to our services. For this reason, we broaden the number of ips available for the default svc in order to have free ips available for our test svc.
=> Assignement tests: make the generic pool broader

.github/workflows/ci.yaml, charts/metallb/README.md, charts/metallb/values.yaml, config/frr/speaker-patch.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, e2etest/pkg/frr/container/container.go, internal/bgp/frr/docker_test.go, tasks.py
As the frrouting org is moving the official frr images to the quay.io registry, this PR changes the FRR image to point to quay.
Signed-off-by: liornoy <lnoy@redhat.com>
=> Change FRR image to the quay.io repo

e2etest/l2tests/assignment.go
This changes default ip pool scope only to test namespace so that it avoids ip assignment to a service outside test namespace which is already waiting for lb ip address then it leads bigger churn of ip pool reconcile attempts while running the tests.
=> E2E: Reduce default ip pool scope to namespace

e2etest/bgptests/infra_setup.go
When running on host mode, the nexthop container is not running so getting the routes will fail. So, we check if the the routes are not fetched because the container is not there, and in case we continue and not error.
This fixes the error on aftersuite when running the tests in host mode.
=> E2E: don't exit if not able to find multihopRoutes

internal/k8s/controllers/config_controller.go, internal/k8s/controllers/config_controller_test.go
The configuration controller is triggered by multiple events, including all the secrets in the metallb's namespace. This cause a cascade effect of reprocessing all the services which is not necessary.
Here we compare the last processed configuration with the one we just produced (which takes into account of non used secrets and non used namespaces, for example), limiting configuration reload events to those that really are changing the metallb's internal configuration.
On top of that, in order to keep the node label test effective, the implementation of the reconciliation function is deferred to a local function that can be overridden by the tests.
Fixes https://github.com/metallb/metallb/issues/1770
=> Config Controller: ignore changes that are not relevant

controller/main.go, controller/service.go
The method convergeBalancer returns always True. This boolean is not
needed, therefore it is removed.
=> Remove return value for convergeBalancer

internal/bgp/frr/frr.go, internal/bgp/frr/frr_vrf_test.go, internal/bgp/frr/testdata/TestTwoSessionsSameIPRouterIDASNVRF.golden, internal/config/validation.go, internal/config/validation_test.go
With FRR, it's fair to have the same ip for different peers if they belong to different vrfs.
=> FRR Mode: allow overlapping ips in case of vrfs

configsamples/ipaddresspool_with_selector.yaml, controller/controller_test.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, website/content/configuration/_advanced_ipaddresspool_configuration.md
This adds web content for ip pool with service allocation feature and a sample yaml file for such configuration.
=> Add documentation for ip pool service allocation

.github/workflows/ci.yaml, config/crd/bases/metallb.io_addresspools.yaml, config/crd/bases/metallb.io_bfdprofiles.yaml, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_communities.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/crd/bases/metallb.io_l2advertisements.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, config/webhook/manifests.yaml, tasks.py, website/content/release-notes/_index.md
Bumping the manifests relies on the version that is installed on the
local machine. This means, calling it on different machines might lead
to different results, having inconsistently generated files.
Here we install the binary to a local path with a pinned version and we
consume it from there.
Also, bumping the release version in the release notes to avoid the need
of having another pr queued.
=> Pin the controller-gen version used by tasks

website/content/configuration/_advanced_l2_configuration.md
Fixes typo in advanced l2 configuration page, 'whill' -> 'will'
=> Fixes typo in advanced l2 configuration page

charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.yaml
Hi Metallb Team,
we have several labels that we like to add to our k8s resources. Some are purely for humans, while others are technically relevant (f.e. tracing, NetworkPolicies).
I noticed that your helm chart does not offer this functionality, so I wanted to help by adding a little code that enables users to specify additionaLabels in the values.yaml which will be picked up by the speaker+controller Daemonsets.
If there is anything missing or you disagree with the solution, I'm always open to feedback :) 
Also: Thanks for providing a helm chart in the first place!
=> Enable adding of additional Labels to speaker+controller

go.mod, go.sum, internal/bgp/native/native.go
Use the TCPMD5Sig type and the corresponding SetsockoptTCPMD5Sig func added upstream in golang.org/x/sys v0.6.0
=> internal/bgp/native: use SetsockoptTCPMD5Sig from golang.org/x/sys/unix

go.mod
Fixed #1842 . 
Tested with inv lint, inv test, and inv build.
=> Change k8s.io/client-go to v0.26.1

charts/metallb/README.md, charts/metallb/templates/exclude-l2-config.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, config/controllers/speaker.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, config/native/exclude-l2-config.yaml, config/native/kustomization.yaml, internal/layer2/announcer.go, speaker/main.go
In arp mode, Some common virtual interfaces should not be used to announce services, such as kube-ipvs0, docker0, etc. This PR will dispatch these common virtual interfaces. 
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>
https://github.com/metallb/metallb/issues/1727
l2: exclude common virtual interfaces for announce services.
=> l2: exclude common virtual interfaces for announce services

e2etest/bgptests/bgp.go, e2etest/bgptests/validate.go, e2etest/pkg/frr/bgp.go
We want to verify that each container is able to send routes and that changing the configmap before the configuration is applied and after the configuration is applied still works.
So, we split the all in one test in a baseline where we check metallb should not accept incoming routes, and to another one where we validate each external container is able to send routes.
=> E2E Tests: rewrite the check routes injected test

e2etest/l2tests/assignment.go, e2etest/pkg/k8s/namespace.go
This prevents version skews in case the ns is modified after the creation.
=> E2E: read the namespace before changing the labels

e2etest/l2tests/assignment.go, e2etest/pkg/k8s/namespace.go
Depending on the platform we run the test, the level privileged label can be added or removed. Because of this, we rely only on the extra label we add so the test has more control on the execution.
=> E2E ns label test: use only the extra label for selection

e2etest/l2tests/interface_selector.go, e2etest/l2tests/l2.go, e2etest/l2tests/node_selector.go, e2etest/l2tests/node_service.go, speaker/main.go
After discovering flakes in the L2 tests around the networkUnavailable condition feature, this commit fixes:
1. Wrap "advertisingNodeFromMAC" with Eventually to give the speakers enough time to settle.
2. In the speaker's "SetNode" function: fixed the name of the node we're passing to the isNetworkConditionChanged function.
fixes #1904
=> Fix the NetworkUnavailable condition L2 flakes

tasks.py
Currently, the `dev-env` task from tasks.py builds new docker images from the source code, and the old images stay untouched, accumulating over and time taking up space.
This commit adds the logic for deleting the old metallb dev images when invoking dev-env.
We wrap it up with `try` and `except` to ignore the failure: Docker Image doesn't exist.
fixes #1325
=> tasks.py - delete old metallb dev images

.github/workflows/composite/setup/action.yaml
This commit upgrades the cancel-workflow-action to the latest v0.11.0,
due to the following deprecation notice (seen as warning messages in the actions tab):
```
Node.js 12 actions are deprecated. Please update the following actions
to use Node.js 16: styfle/cancel-workflow-action@0.9.1.
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
As mentioned in the cancel-workflow-action README, we should consider
using the native concurrency property to cancel workflows:
https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
=> Upgrade the cancel-workflow-action

config/native/kustomization.yaml
This removes the deprecated kustomization vars discussed in #1911 . I used `kustomize build` and compared the output before and after this change and it seems to output the same code.
=> Remove deprecated kustomization vars

api/v1beta1/bgpadvertisement_types.go, api/v1beta1/community_types.go, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_communities.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, e2etest/.gitignore, e2etest/bgptests/bgp.go, e2etest/pkg/frr/bgp.go, e2etest/webhookstests/webhooks.go, internal/bgp/bgp.go, internal/bgp/community/community.go, internal/bgp/community/community_test.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/frr_vrf_test.go, internal/bgp/frr/templates/filters.tmpl, internal/bgp/frr/testdata/TestLargeCommunities.golden, internal/bgp/native/messages.go, internal/bgp/native/messages_test.go, internal/config/config.go, internal/config/config_test.go, internal/config/validation.go, internal/config/validation_test.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, website/content/apis/_index.md
This patch only implements large communities but the format is compatible with a future implementation of extended communities.
Community types are distinguished by using Juniper style syntax, thus <AS number>:<community value>,<type>:<administrator>:<assigned-number>, large:<global administrator>:<localdata part 1>:<localdata part 2> for each of the respective types legacy, extended and large communities.
Implements https://issues.redhat.com/browse/RFE-3924
=> Add support for BGP large communities

controller/controller_test.go, controller/service.go
When a service requests a specific LB IP(s) and address pool via annotations, these must be compatible.
Fixes #1916
=> Verify LB ip and address pool annotations compatibility

design/crd-status.md
Exposing part of the internal state was not possible until the introduction of CRD based configuration, and now that we have it it makes sense to expose part of the state in order to ease debugging and troubleshooting.
=> Design: add a proposal to expose MetalLB's status via CRDs

charts/metallb/README.md, charts/metallb/values.yaml
The FRR implementation is now mature, and it is where all our efforts are going, so it makes sense to have it as the default implementation.
=> Have the FRR one the default implementation when deploying with charts

e2etest/bgptests/bgp.go, e2etest/bgptests/validate.go, e2etest/pkg/frr/config/config.go
Users requiring routes to come from outside may need to filter only allowed routes. Here we validate that it works.
=> E2E: extend the "inject" test with prefix lists

controller/main.go, internal/allocator/allocator.go
This prevents the unnecessary reprocess of all services when a service with no LB IP assigned is deleted.
=> Trigger reprocessall event only when an ip has been unassigned

controller/main.go, controller/service.go
When convergeBalancer fails to assign an LB IP to a unallocated service, the response of the service handler was SyncStateSuccess which errounously indicates that the service converged. This PR sets the response to SyncStateErrorNoRetry.
No functional changes, just an extra error log message from the switch of the service controller.
=> Fix syncState response for unconverged services

internal/allocator/allocator.go
The pool is directly obtained from the alloc structure instead of looping through all pools.
=> Simplify pool allocated search

e2etest/bgptests/bgp.go, e2etest/bgptests/bgp_multiprotocol.go, e2etest/bgptests/metrics.go, e2etest/bgptests/node_selector.go, e2etest/bgptests/validate.go, e2etest/l2tests/interface_selector.go, e2etest/l2tests/l2.go, e2etest/pkg/wget/wget.go, internal/k8s/controllers/config_controller_test.go, internal/k8s/controllers/node_controller_test.go
This PR includes 2 commits that modify the e2etest:
1. Add more verbose logs to tests and modify the `wget` error output to include the std message.
2. Modify Gomega error assertions to be aligned with best practices.
=> e2etests: logs and error output modifications

dev-env/README.md, dev-env/audit-policy.yaml, tasks.py
Audit logs are useful to understand the interaction between metallb and the api server, to see if metallb is behaving correctly. Here we add a parameter to enable them.
=> Allow enabling the audit logs on kind

e2etest/l2tests/assignment.go
We apply the labels to the ns right after its creation. Because of this, if the namespace is changed by the cluster we might get a "the object has been modified" error.
=> E2E assignement tests: retry to apply the labels

internal/k8s/controllers/pool_controller.go
This prevents the pool controller to trigger the reprocess all event when there are no changes in the pools.
=> Trigger reprocess all event only when pool changes

e2etest/README.md, tasks.py
This commit adds a "ginkgo_params" flag to the e2etests task. This addition is to enable developers to insert ginkgo params that are not already covered by existing parameters (focus and skip)
A simple example of this feature is running the e2etests with the --until-it-fails flag, which is handy for catching flaky tests.
The implementation injects the value of this new parameter in the ginkgo test run command. and It's possible to add numerous ginkgo params for example:
`invoke e2etest --ginkgo-params="--until-it-fails -v --focus=L2"`
Also, added a mention of this new flag in the e2etests/README.md.
Fixed #1955
=> Add "ginkgo_params" flag to the e2etests task

internal/bgp/frr/frr_bfd_test.go, internal/bgp/frr/testdata/TestBFDProfileThenDelete.golden, internal/bgp/native/native.go, speaker/bgp_controller.go
When a bfd profile is deleted, the sync is not called and we leave the bfd profile filled even if it was deleted on the CR side.
Additionally, we add a unit test to validate the deletion works properly.
=> BGP: invoke SyncBFDProfiles on empty lists too

frr-tools/metrics/liveness/liveness.go
The missing part was referencing the wrong map.
=> Fix the liveness failure log

internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/config_conversion.go, internal/k8s/controllers/config_conversion_test.go, internal/k8s/controllers/pool_controller.go
When translating the configuration coming from the k8s api to the internal one, the outcome depends on the order in which the cache returns us the various items. This may cause unnecessary reloads.
In order to avoid this, we pre-order the list of items to feed the conversion with.
The sorting is done in a conversion function in the controller (rather than the config package) in order to make it harder to forget to add the sorting action.
=> Make the configuration conversion stable

internal/layer2/announcer.go
This commit changes the log level from Info to Debug as this log is called every 10 seconds and spams/bloats the speaker's logs.
See example:
```
{"caller":"announcer.go:76","event":"announced interface to exclude","interface":"lo","level":"info","ts":"2023-07-01T12:49:50Z"}
{"caller":"announcer.go:76","event":"announced interface to exclude","interface":"veth9d893234","level":"info","ts":"2023-07-01T12:49:50Z"}
{"caller":"announcer.go:76","event":"announced interface to exclude","interface":"veth1d7c0ce9","level":"info","ts":"2023-07-01T12:49:50Z"}
{"caller":"announcer.go:76","event":"announced interface to exclude","interface":"veth940dd62c","level":"info","ts":"2023-07-01T12:49:50Z"}
{"caller":"announcer.go:76","event":"announced interface to …
```
=> Change 'interface to exclude' log level

charts/metallb/templates/controller.yaml, charts/metallb/templates/exclude-l2-config.yaml, charts/metallb/templates/rbac.yaml, charts/metallb/templates/service-accounts.yaml, charts/metallb/templates/servicemonitor.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/templates/webhooks.yaml
=> fix: add missing namespace to helm chart templates

e2etest/bgptests/bgp.go, e2etest/pkg/frr/config/config.go
Until now we were testing injection with single stack, so the "toAnnounce" prefixes where added either to the v4 or to the v6 family section. Here we change it to allow the user to specify both ipv4 prefixes and ipv6 prefixes.
=> E2E: allow to specify v4 / v6 prefixes to inject

e2etest/bgptests/infra_setup.go, e2etest/e2etest_suite_test.go, tasks.py
Running the e2e tests with host container allows only of the 4 degrees at the time (assuming the host is one hop away from the cluster). Here we allow setting the container as ebgp or ibgp to cover at least two.
=> E2E: allow to set the host container as ebgp or ibgp

configmaptocrs/main.go, configmaptocrs/testdata/configmap-data/config-data-bfdprofile.golden, configmaptocrs/testdata/configmap-yaml/config-yaml-bfdprofile.golden
Fix Gosec error inside the configmaptocrs:
G601 (CWE-118): Implicit memory aliasing in for loop. (Confidence: MEDIUM, Severity: MEDIUM)
This is also a bug fix because it didn't create
the correct echoMode and passiveMode values in the CRD. Updated the golden files.
=> Fix Gosec error in the configmaptocrs

charts/metallb/templates/speaker.yaml
This PR implements the additional fields available to a `livenessProbe` for the `frr` container.  The rationale is that I run k8s nodes on SOQuartz arm64 boards and they sometimes can take >1 second to respond to `livenessProbe` queries.  Because the fields were previously undefined, `timeoutSeconds` was defaulting to `1`, leading to the `frr` container falling into CrashLoopBackOff.
=> add more livenessProbe configurability in helm chart for frr container

website/content/configuration/_index.md
The link on the page was 404'ing, I changed it to the link the side bar has.
=> Fixing typo for Advanced IPAddressPool

speaker/layer2_controller.go
we should skip announcing L2 service and log it when no available nodes
Fixes https://github.com/metallb/metallb/issues/2005
=> improve speaker logging when no available nodes

internal/k8s/epslices/endpoint_slices.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go
Fixes https://github.com/metallb/metallb/issues/2074
accepted.
This PR switches from using `eps.ready` to `eps.serving`.
The idea behind …
=> Switched from eps.ready to eps.serving

controller/main.go, internal/k8s/k8s.go, internal/k8s/webhook.go
It appears that webhookSecretName is hardcoded to 'webhook-server-cert', With this PR, we can configure it via the controller's flag: --webhook-secret.
Fixes: https://github.com/metallb/metallb/issues/1993
=> make webhook secret's name configurable

controller/controller_test.go, controller/main.go, controller/service.go, e2etest/l2tests/assignment.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go
This is https://github.com/metallb/metallb/pull/1948 plus the fixes suggested in the last phase of the PR.
Pool changes might invalidate the LB IPs of services. When this happens, the pool controller ignores the new configuration and continues operating with the current one. This PR modifies this behavior by always accepting the new configuration and letting the service controller to clear the IPs of the affected services.
Fixes https://github.com/metallb/metallb/issues/462
=> Remove IP verifications in SetPools

e2etest/pkg/frr/parse.go, e2etest/pkg/frr/parse_test.go
We might require this from frr-k8s tests.
=> E2E: parse also configured keepalive and holdtime in neighbors

configmaptocrs/Dockerfile, controller/Dockerfile, speaker/Dockerfile
This is a small PR to keep up to date with the latest patch version of golang in the dockerfiles. 
The .9 and .10 versions have security fixes for CVEs that may show up in scans of this image (specifically https://github.com/golang/go/issues/63417)
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.9+label%3ACherryPickApproved
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.10+label%3ACherryPickApproved
=> Update dockerfiles to build with latest golang patch

website/content/community/release-process.md
Not sure is still relevant and/or up to date given the current https://github.com/metallb/metallb/blob/main/.github/workflows/publish.yaml
=> Get rid of circleci refs in docs

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
Small addition to support setting the pod level security context on the speaker daemonset.
This is useful in some environments where explicit securityContext must be set for pods, or potentially when using a rebuilt image with a different (user/group could be different).
=> Add support for speaker securityContext

internal/ipfamily/ipfamily.go, internal/ipfamily/ipfamily_test.go
Fixes a small part where we considered an invalid address as an IPv6 one
=> Fix parsing invalid addresses as IPv6

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
The bind address for memberlist is currently always set to the pod's IP address:
` - name: METALLB_ML_BIND_ADDR
valueFrom:
fieldRef:
fieldPath: status.podIP`
This PR allows this to be customised. 
In my scenario I wanted it to listen to a different address as the speaker pods were connecting to each other via a VIP which didn't work unless I changed the bind address.
The current behaviour is kept as the default behaviour, but it can be overridden using the new `speaker.memberlist.mlBindAddrOverride` configuration in values.yaml.
=> Allow custom bind address for memberlist

controller/main.go, internal/k8s/k8s.go
This is optional, and should remediate the http2 fast reset bug.
=> Disable http2 for the controller webhook

website/content/troubleshooting/_index.md
There is currently an issue with some devices where they do not properly work when using WiFi.
I wan into this on my Raspberry Pi and it took me quite some time troubleshooting until I ran into this issue: https://github.com/metallb/metallb/issues/284
After enabling promiscuous mode it has worked flawlessly.
This PR adds this information to the troubleshooting section of the website to save others the pain of hunting this down via other sources.
=> Docs: Add promiscuous mode workaround for L2 on WiFi

internal/speakerlist/speakerlist.go
`SpeakerList` currently configures memberlist to use AES-128 to encrypt the messages involved in the cluster membership management. This PR increases the size of `SecretKey` to make memberlist use AES-256 instead.
Closes #1982.
=> Use AES-256 for memberlist message encryption

charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
In the environment we are using we would like to deploy a container right next to every MetalLB Speaker. The easiest and most reliable way for us would be to use the functionality this PR would add.
If you want me to add this to the `controller.yaml` too, feel free to tell me.
=> feat(helmchart): add extraContainers to speaker

e2etest/e2etest_suite_test.go
Since we updated the controller-runtime, e2e execution produces an annoying "[controller-runtime] log.SetLogger(...) was never called" message. Here we set the logger to the gingko writer to make it happy.
=> E2E: set the controller-runtime logger in BeforeSuite

tasks.py
Fix "SyntaxWarning" regex errors that Python is complaining about in the latest version, by adding a "r" character before strings with escape sequence.
=> tasks.py: Fix regex errors

charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/values.yaml, config/controllers/controller.yaml, config/manifests/metallb-frr-k8s.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, controller/main.go, go.mod, go.sum, internal/k8s/k8s.go
This PR changes controller webhook server tls security config
changes:
- Use secure tls-cipher-suites to solve [CVE-2016-2183- Red Hat Customer Portal](https://access.redhat.com/security/cve/cve-2016-2183). 
- Allow configure tls-cipher-suites and tls-min-version via command line params, e.g. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/,  If omitted, the default PreferredTLSCipherNames cipher suites will be used.
Before
```
> kubectl port-forward svc/metallb-webhook-service 1443:443 &
[1] 20151
Forwarding from 127.0.0.1:1443 -> 9443
Forwarding from [::1]:1443 -> 9443
Handling connection for 1443
> nmap --script ssl-enum-ciphers 1443 127.0.0.1
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-14 14:07 CST
Nmap scan report for localhost (127.0.0.1)
Host …
```
=> Allow the controller configure tls-cipher-suites and tls-min-version via command line params 

.github/workflows/ci.yaml, website/content/release-notes/_index.md
Adding a CI rule that forces the contributor to touch the release notes. This should prevent mistakes / make the maintainers' life easier without resorting to do PR archeology to build the changelog.
=> CI: enforce the release notes

configmaptocrs/Dockerfile, controller/Dockerfile, speaker/Dockerfile, website/content/release-notes/_index.md
The goal of this PR is to speed up Docker builds, because I'm on a slow network and every time I ran `inv dev-env` it took a long time.
1. I moved towards the bottom lines, such as
```
ARG GIT_COMMIT=dev
ARG GIT_BRANCH=dev
```
so they don't invalidate the other docker layers when the value changes (i.e., go mod download).
2. The second thing is to reduce the number of layers by replacing instructions such as:
```
COPY go.mod go.sum ./
```
with
```
--mount=type=bind,source=go.sum,target=go.sum \
--mount=type=bind,source=go.mod,target=go.mod \
```
this way the files are mounted from the host instead of copied to a new layer.
3. I added a cache mount for downloaded go modules:
```
RUN --mount=type=cache,target=/go/pkg/mod/ \
...
go mod download -x
```
=> controller: improve docker build cache

website/content/release-notes/.gitattributes
The rel notes are appended, so it makes sense to do union instead of merging, otherwise each PR will cause a conflict.
=> RelNotes: union instead of merge

config/manifests/metallb-frr-k8s-prometheus.yaml, config/prometheus-frr-k8s/kustomization.yaml, config/prometheus-frr-k8s/relabel-metrics.yaml, e2etest/bgptests/metrics.go, tasks.py, website/content/release-notes/_index.md
We would like to expose the frr metrics coming from frr-k8s as metallb's because it is the same set of metrics (for frr mode) and would make the integration smoother when the servicemonitors are set up in a similar way.
=> CI/E2E: relabel the frr metrics from frr-k8s to show as MetalLB's

configmaptocrs/Dockerfile, controller/Dockerfile, speaker/Dockerfile, website/content/release-notes/_index.md
This updates the dockerfiles to the latest go minor version, 1.20.12.
Included is a fix for CVE - https://github.com/golang/go/issues/64433
=> Update to Go 1.20.12

tasks.py, website/content/release-notes/_index.md
Change the default BGP mode in the tasks.py dev-env command to FRR.
The rationale for this is that we no longer develop features for the native mode, and it makes sense to set the development environment to default to FRR.
=> Change default BGP mode to frr in dev-env command

internal/config/validator.go, internal/config/validator_test.go, website/content/release-notes/_index.md
Fixed  #2173 
There are TransientErrors that can occasionally result in overlooking genuine issues. The solution is to reset the fields that might be causing a TransientError.
=> Webhook does not process transient errors properly

website/content/concepts/layer2.md
I was just skimming through the docs of the Layer 2 mode and found this small typo.
=> docs: fix typo in layer 2 mode docs

tasks.py, website/content/release-notes/_index.md
When GOBIN is already set, go install will install the binary to that path. However,  line 'run("{}/bin/controller-gen...' expects controller-gen to be installed under build/bin/controller-gen. Force GOBIN to the correct value, always.
Reported-at: https://github.com/metallb/metallb/issues/2218
=> Override GOBIN for inv dev-env

e2etest/l2tests/l2.go, e2etest/pkg/config/validate.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/allocator/stats.go, internal/k8s/controllers/reconciliation_test.go, website/content/release-notes/_index.md
issue: https://github.com/metallb/metallb/issues/2150
=> Metrics: add ipv4/6 addresses_in_use_total and addresses_total

internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestTwoAdvertisementsDuplicate.golden, website/content/release-notes/_index.md
Passing multiple advertisements with the same prefix to the template causes duplicate entries. This happens for example when the shared ip annotation is used with the services.
Since a given advertisement has the related peers as fields, the right place to squash is when we manage the advertisements related to a given neighbor.
=> FRR: squash advertisements with the same prefix

e2etest/l2tests/l2.go, internal/k8s/nodes/nodes.go, speaker/bgp_controller.go, speaker/layer2_controller.go, speaker/main.go, tasks.py, website/content/release-notes/_index.md
The label specifies that the node should not be considered as a target for external load-balancers which use nodes as a second hop.
Fixed https://github.com/metallb/metallb/issues/2021
=> Implement NodeExcludeBalancers to exclude nodes as external loadbalancer

.github/workflows/ci.yaml, tasks.py
We saw a flake where the first test fails, probably because the lb exclusion is not effective yet. So here we:
- move the exclusion from the e2e command to the dev-env command, so it will work when testing / tinkering too
- active wait until all the labels are removed
=> dev-env: wait until the lb exclusion is effective

tasks.py
We create a temporary folder each time to avoid asking root permissions to the user.
=> Dev-env -p bgp: pass a temp dir to frr

charts/metallb/templates/speaker.yaml, website/content/release-notes/_index.md
The creation of the metrics-certs volume is conditioned by FRR mode, while it should only be conditioned by the presence of the name of the secret in the values.
=> Charts: fix the metrics-certs volume of the speaker

website/content/release-notes/_index.md, website/content/usage/_index.md
k8s now supports mixed protocol services of type LoadBalancer
Mixed protocol support was merged in k8s with [kubernetes/pull/94028](https://github.com/kubernetes/kubernetes/pull/94028).
accepted.
#<issue number>" in the PR …
=> Remove outdated information about k8s mixed protocol support

charts/metallb/templates/controller.yaml, charts/metallb/templates/webhooks.yaml, config/controllers/controller.yaml, config/manifests/metallb-frr-k8s-prometheus.yaml, config/manifests/metallb-frr-k8s.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, config/webhook/secret.yaml, controller/main.go, website/LICENSE, website/content/release-notes/_index.md
Rename webhook_service/webhook_cert name to avoid name conflicts with other resources in the cluster.
Fixes https://github.com/metallb/metallb/issues/2174
=> Make the name of the webhook certs more metallb specific

go.mod, internal/logging/logging.go, website/content/release-notes/_index.md
Until now, controller-runtime logs were running with the default. Here we propagate the loglevel parameter to those logs too.
Note that this might cause less logs than we are used to, when triaging (but it should honor the desire of the user).
Fixes https://github.com/metallb/metallb/issues/2161
=> Logging: propagate the log level to the controller-runtime logs

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go, speaker/main.go, website/content/release-notes/_index.md, website/content/troubleshooting/_index.md
MetalLB now honors the node.kubernetes.io/exclude-from-external-load-balancers
but this might harm some deployments where there is only one node and
kubeadm still labels the control plane with such label.
Here we provide a knob to disable the behaviour and make metallb work in
such scenarios.
=> Provide a ignore-exclude-lb flag

internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/templates/filters.tmpl, internal/bgp/frr/testdata/TestLargeCommunities.golden, internal/bgp/frr/testdata/TestManyAdvertisementsSameCommunity.golden, internal/bgp/frr/testdata/TestSingleAdvertisement.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden, internal/bgp/frr/testdata/TestSingleAdvertisementChangeVRF.golden, internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden, internal/bgp/frr/testdata/TestSingleAdvertisementVRF.golden, internal/bgp/frr/testdata/TestTwoAdvertisements.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsDuplicate.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessionsOneVRF.golden, internal/bgp/frr/testdata/TestTwoAdvertisementsVRF.golden, website/content/release-notes/_index.md
The current implementation creates one route map per localpref / community, duplicating the same route-map for each advertisement (while what we really need is one route map, many prefix-lists entries, one per service).
Here we collect all the communities / localpref / large communities per neighbor, and we use it to generate a route-map per neighbor per community / localpref only once.
=> Communities / LocalPref routemaps: create one route map per neigh

.github/pull_request_template.md, .github/workflows/ci.yaml, .github/workflows/classify.yaml, website/content/community/release-process.md, website/gen_relnotes.sh
Trying to migrate the current way to enforce the release notes:
- remove the mandatory need to change the rel notes
- provide a pr template aligned to k8s, with a field for rel notes
- provide a gh action to assign the right label to the pr, that can be used by the tool
When this is established, it will be possible to use the tool to generate the release notes automatically.
This goes under the assumption that no cherry-pick is done without a corresponding PR.
/kind cleanup
=> Release notes: use the k8s release tool

.github/workflows/classify.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We don't want to allow the labeler job to change ANY PR, just the one the action is currently running against.
From the docs:
This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does.
```release-note
NONE
```
=> CI: trigger the add labels job on pull_request_target

website/content/installation/_index.md
**Is this a BUG FIX or a FEATURE ?**: /kind documentation
Fix the typo on the installation page.
`MetallLB` => `MetalLB`
NONE
```release-note
NONE
```
=> Docs: fix the typo on the installation page

charts/metallb/templates/exclude-l2-config.yaml
/kind cleanup
- no need to install "metallb-excludel2" cm, when speaker component is disabled
- added common labels for "metallb-excludel2" cm the same way as for another manifests
NONE
```release-note
The metallb-excludel2 configmap is not deployed from the Helm chart if the speaker is disabled.
```
=> Charts: don't deploy metallb-excludel2 cm if the speaker is disabled

.github/workflows/classify.yaml, website/content/release-notes/.gitattributes
We run a simple check against the release-note entry of the PR body, to notify the users that that section is required for release notes.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This can't be tested as part of the PR itself, however I tested it here https://github.com/fedepaol/relnotestexperients/pull/19
```release-note
NONE
```
=> PR classify: fail if there is no text for rel notes

.github/workflows/ci.yaml, e2etest/l2tests/interface_selector.go, e2etest/l2tests/l2.go, internal/k8s/k8s.go, speaker/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Because of https://github.com/metallb/metallb/issues/2311 we are going to move the status instances to the metallb namespace. This might require a change in the permissions too (from cluster to namespaced) so the new version of MetalLB might not be able to delete the "legacy" instances of the CRD because they belong to namespaces the new metallb might not have permissions on.
Because of this, we hide the feature behind a flag, effectively disabling it until the issue is fixed. …
=> Speaker: hide the L2ServiceStatus generation behind a flag

speaker/bgp_controller.go
Instead of forcing users to turn on debug logging to figure out why their BGP announcements aren't going out, make these warnings.
This is pretty trivial, but I won't be upset if nobody likes it.
/kind cleanup
```release-note
The log level of the logs for skipping the BGP announcement because of the 'node.kubernetes.io/exclude-from-external-load-balancer' label and the network unavailable condition are now warning instead of debug.
```
=> Warn users when skipping BGP announcements

tasks.py
In case one of the configured buildx contexts are unavailable (e.g. remote host not reachable), docker buildx ls will hang for several seconds.
/kind cleanup
The container build task _docker_build_cmd checks for buildx support. It uses `docker buildx ls`. However, if docker was configured with multiple contexts and some of those are not reachable for some reason the command waits for timeouts.
```release-note
NONE
```
=> Use docker buildx version instead of ls for buildx check.

.github/workflows/classify.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Dependabot doesn't care about labels, so we skip the PR classification job on its prs.
```release-note
NONE
```
=> CI: don't run the labeler job on dependabot prs

configmaptocrs/Dockerfile, controller/Dockerfile, speaker/Dockerfile
/kind cleanup
Updates to the latest 1.21.x version, which includes a net/http CVE fix - https://github.com/golang/go/issues?q=milestone%3AGo1.21.9+label%3ACherryPickApproved
N/A
```release-note
NONE
```
=> chore: update go to 1.21.9

internal/k8s/epslices/endpoint_slices.go, internal/k8s/epslices/endpoint_slices_test.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go
Fixes #2336
>
/kind bug
> /kind design
> /kind flake
```release-note
Fix the handling of readyness conditions of endpointslices: instead of looking at the serving condition first, we look at the ready condition. This allows metallb to respect the publishNotReadyAddresses field of the services.
```
=> Fix the handling of readyness conditions of endpointslices

internal/config/config.go, internal/config/config_test.go
/kind cleanup
The current return error on the validation webhook looks like
```
Error from server (Forbidden): error when creating "peers.yaml": admission webhook "bgppeersvalidationwebhook.metallb.io" denied the request: parsing peer peer-with-kt-greater-than-ht: invalid keepaliveTime {"1m0s"}
```
which does not clue the real reason why that fails validation which is that keepalive time is greater than holdtime.
```release-note
NONE
```
=> Improve error message when keepalivetime is invalid

.github/workflows/ci.yaml, .github/workflows/cifuzz.yml, .github/workflows/composite/collectlogs/action.yaml, .github/workflows/composite/setup/action.yaml
/kind cleanup
This PR cleans up the composite workflow(s) action dependency. These are running on fairly old versions of the actions and are throwing the following warnings in CI
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v3, actions/download-artifact@v3, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
```release-note
NONE
```
=> Bump composite workflow actions

charts/metallb/templates/servicemonitor.yaml
/kind bug
Fixes #2389
You can verify the rendered template for metallb-spekaer-monitor-service as follows;
1. Render helm chart
```
helm template metallb  --set prometheus.serviceMonitor.enabled=true --set prometheus.serviceAccount=prometheus-monitoring-kube-prometheus --set prometheus.namespace=monitoring > /tmp/metallb-new.yaml
```
2. Check `/tmp/metallb-new.yaml` file for `metallb-speaker-monitor-service` if it contains label `app.kubernetes.io/name` with value `metallb`
```release-note
Propagate the metallb labels to the speaker's service monitor service
```
=> Added speaker monitor service labels

charts/metallb/templates/speaker.yaml, config/frr/speaker-patch.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, configmaptocrs/Dockerfile, controller/Dockerfile, e2etest/l2tests/interface_selector.go, e2etest/pkg/executor/executor.go, frr-tools/cp-tool/cp-tool.go, speaker/Dockerfile, website/content/troubleshooting/_index.md
Inspired by https://github.com/metallb/metallb/pull/2117
fixes https://github.com/metallb/metallb/issues/2110
A big thank you to @oribon and @georgettica for the detail discussion in #2117 which is **the** design document I followed to this solution. Also appreciate @oribon 's help during design implementation, that I was able to run local integration and e2e tests! 
/kind feature
gcr.io/distroless/static base image is used to replace the original docker.io/alpine image, for a distroless solution that controller and speaker images will be built from scratch. Since distroless base image has no shell entry, there are two major impacts with this solution:
1. Some of the frr init containers which need to move files …
=> Use distroless image to build controller and speaker containers

charts/metallb/templates/speaker.yaml, config/frr/speaker-patch.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml
frr-metrics liveness probe runs a show daemons command repeatedly and append that at the end of a file. When the file is longer than 1k lines the history gets truncated which involves a few system calls like renames. When the system is under stress this rename call can take a few seconds, exceeding the timeout of the liveness probe.
When this happens repeatedly frr process gets restarted.
This was noticed as part of the investigation in
https://issues.redhat.com/browse/OCPBUGS-34761?focusedId=24850879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24850879
>
/kind bug
> /kind design
> /kind flake
> …
=> Charts: don't log history in liveness probe

internal/k8s/controllers/node_controller.go
There are cases wherein a node's condition like "lastHeartbeatTime" can get updated every few seconds waking up node reconciler. This is just a no-op. But the logs get inundated with "start reconcile" and "end reconcile" messages. This gets worse in large clusters.
Fixed #2451
>
/kind bug
> /kind design
> /kind flake
```release-note
Limit processing the node events when label changes or when only the NetworkUnavailable condition changes, as opposed to processing when every condition (including heartbeats!) changes.
```
=> Care only about NetworkUnavailable condition.

e2etest/bgptests/bgp.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/parse.go, e2etest/pkg/frr/parse_test.go, e2etest/pkg/frr/validation.go, internal/bgp/frr/templates/neighborsession.tmpl, internal/bgp/frr/testdata/TestBFDWithSession.golden
>
/kind bug
> /kind design
> /kind flake
The generated configuration file has the format
`neighbor xxxx bfd profile zzz`
which works, but causes session flapping whenever the configuration is
reloaded, as the converted configuration contains two entries:
```
neighbor xxxx bfd
neighbor xxxx bfd profile zzz
```
Reloading the configuration causes the first line to be removed:
```
Lines To Delete
===============
ip forwarding
ipv6 forwarding
router bgp 64520
no neighbor 10.74.239.52 bfd
```
which causes the session to flap. Here we generate also the
`neighbor xxxx bfd`
entry to …
=> Prevent session flapping when BFD is enabled and services are added / removed

charts/metallb/templates/prometheusrules.yaml
/kind bug
PrometheusRule labels doesn't match default configuration. This results in no active alerts by default. 
Example previously:
```
expr: metallb_bgp_session_up{job="metallb"} == 0
```
Example now:
```
expr: metallb_bgp_session_up{job=~"metallb.*"} == 0
```
Metric inside of prometheus (not matching in the previous example):
```
metallb_bgp_session_up{job="metallb-speaker-monitor-service"}
```
Used values for testing:
```
prometheus:
serviceAccount: metallb
namespace: metallb
serviceMonitor:
enabled: true
prometheusRule:
enabled: true
```
```release-note
fix(chart,prometheusrules): alert not matching labels for e.g. speakers
```
=> fix(chart,prometheusrules): alert not matching labels

api/v1beta1/servicel2status_types.go, charts/metallb/charts/crds/templates/crds.yaml, config/crd/bases/metallb.io_servicel2statuses.yaml, config/manifests/metallb-frr-k8s-prometheus.yaml, config/manifests/metallb-frr-k8s.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml
>
/kind bug
> /kind design
> /kind flake
We are adding the same check twice, making flux complain.
```release-note
Fix the double immutable field validation in the ServiceL2Status CRD, which may make the validation of the CRD to fail.
```
=> Service L2 status: remove the duplicate validation

api/v1beta1/bgppeer_types.go, charts/metallb/charts/crds/templates/crds.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/manifests/metallb-frr-k8s-prometheus.yaml, config/manifests/metallb-frr-k8s.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, website/content/configuration/_index.md
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
v1beta2 is around for a while now, deprecating v1beta1 would allow us to (one day!) get rid of the conversion webhooks.
```release-note
Deprecation of BGPPeer v1beta1 in favor of v1beta2.
```
=> Deprecate bgppeerv1beta1

charts/metallb/templates/controller.yaml, charts/metallb/templates/podmonitor.yaml, charts/metallb/templates/rbac.yaml, charts/metallb/templates/service-accounts.yaml, charts/metallb/templates/servicemonitor.yaml
/kind bug
Some speaker related resources and configuration are created even if `speaker.enabled` value is set to `false`. This PR aims to avoid this resources creation and extra configuration when `speaker.enabled` value is set to `false`.
If you have any doubt feel free to ask :smile: 
```release-note
Helm chart: Avoid speaker resources creation when speaker is disabled
```
=> Helm chart: Avoid speaker resources creation when speaker is disabled

internal/safeconvert/convert.go, internal/safeconvert/convertuint32.go, internal/safeconvert/convertuint32_arm.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
On arm, there is no need to check if an int is bigger than uint32 as it
will never be the case. Additionally, leaving the check would cause
building on arm to fail.
```release-note
NONE
```
=> Safeconvert: add arm specific code for int to uint32

charts/metallb/templates/rbac.yaml, config/frr-k8s-external/clusterrole-patch.yaml, config/frr-k8s/clusterrole-patch.yaml, config/manifests/metallb-frr-k8s-prometheus.yaml, config/manifests/metallb-frr-k8s.yaml, config/prometheus-frr-k8s/clusterrole-patch.yaml
We missed adding the rbac for deletion, needed for:
```
if r.desiredConfiguration == nil {
config := &frrv1beta1.FRRConfiguration{ObjectMeta: metav1.ObjectMeta{Name: frrk8s.ConfigName(r.NodeName), Namespace: r.FRRK8sNamespace}}
err := r.Delete(ctx, config)
return ctrl.Result{}, client.IgnoreNotFound(err)
}
```
/kind bug
```release-note
NONE
```
=> Manifests: Add speaker delete FRRConfiguration rbac

controller/main.go, controller/service.go, e2etest/bgptests/bgp.go, e2etest/l2tests/l2.go, e2etest/pkg/service/tweak.go, e2etest/pkg/service/validate.go, internal/allocator/k8salloc/k8salloc.go
This commit deprecates the old annotation prefix metallb.universe.tf in favor of metallb.io.
The introduced change is backwards compatible. E.g., if a services specifies a address-pool using the old prefix, it will still be accepted by the controller. However, if two address-pool annotations are specified the one with the newer prefix (metallb.io/address-pool) has precedence.
If a services uses the old prefix a deprecation warning is generated. The corresponding message will look similar to this one: "Warning: service object contains deprecated metallb annotation metallb.universe.tf/address-pool".
Fixed #2392
**Is this a FEATURE ?**:
/kind feature
Migrate from "metallb.universe.tf" annotation prefix to "metallb.io"
**Special notes for your …
=> Service annotations: change annotation prefix to metallb.io

website/content/configuration/_advanced_bgp_configuration.md, website/content/configuration/calico.md
BUG FIX - on MetalLBs webpage - section "Issues with Calico" Fixed #2512 
>
> /kind bug
> /kind design
> /kind flake
It fixes the Mermaid diagrams on "Issues with Calico" page of the MetalLb website.
Can be validated by running Hugo locally.
The original mermaid diagrams contain blank titles for the subgraphs, so I've simply added incremental spaces instead so they comply with correct Mermaid syntax.
```
NONE
```
=> Added spaces for mermaid diagram subgraph titles to fix syntax error

api/v1beta2/bgppeer_types.go, charts/metallb/charts/crds/templates/crds.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/manifests/metallb-frr-k8s-prometheus.yaml, config/manifests/metallb-frr-k8s.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, e2etest/bgptests/bgp.go, internal/bgp/bgp.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestSingleSessionWithExternalASN.golden, internal/bgp/frr/testdata/TestSingleSessionWithInternalASN.golden, internal/bgp/frrk8s/frrk8s.go, internal/bgp/frrk8s/frrk8s_test.go, internal/bgp/frrk8s/testdata/TestSingleSessionWithExternalASN.golden, internal/bgp/frrk8s/testdata/TestSingleSessionWithInternalASN.golden, internal/config/config.go, internal/config/config_test.go, internal/config/validation.go, internal/config/validation_test.go, speaker/bgp_controller.go, website/content/apis/_index.md
>
/kind feature
Adds support for FRR's "Dynamic ASN", allowing users to specify whether the peer is ibgp or ebgp without explicitly setting its asn. Leverages https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighbor-PEER-remote-as-internal
```release-note
Add DynamicASN field for a BGPPeer, which allows the speaker to detect the AS number to use without explicitly setting it. The new field is mutually exclusive with the existing PeerASN field, and one of them must be specified for any given BGPPeer. 
```
=> Add support for "Dynamic ASN"

design/unnumbered-bgp.md
/kind design
In part of this PR there is
1. A design document about unnumbered BGP peering, discussing implementation and API changes
2. A draft version of how an e2e test can run, more for discussion rather than actually merging that file in that PR.
My plan would be that first we discuss how the raw frr config would look like, then the API in frr-k8s, then in metallb.
Thanks
```release-note
None
```
=> Unnumbered BGP Peering design document

e2etest/e2etest_suite_test.go, tasks.py
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Warning instead of failing if we are not able to export the kind logs. Useful when
setting the report path but running against a running cluster instead of kind.
```release-note
NONE
```
=> Tasks: warn if not able to export kind logs

e2etest/pkg/frr/config/config.go
Currently we are not printing all debug messages for zebra and bfd
subsystem on the peers side in the e2etests. Therefore tests like
graceful restart test and future tests with BFD are harder to debug in
case of failure. This commit increases the debug in the frr config to be
the same as the frr config on the node, which includes zebra,bfd.
>
> /kind bug
> /kind design
/kind flake
-->
```release-note
NONE
```
=> E2E: increase debugging for the external peers

internal/config/config.go
/kind cleanup
Use the functionality provided by the Go standard library `slices` package since Go 1.21 instead of the deprecated functions in the `k8s.io/utils/strings/slices` package.
```release-note
NONE
```
=> internal/config: Replace k8s.io/utils/strings/slices by Go stdlib slices

internal/bgp/frrk8s/frrk8s.go, internal/bgp/frrk8s/frrk8s_test.go, internal/bgp/frrk8s/testdata/TestTwoAdvertisementsWithSamePrefix.golden
/kind bug
when we enter 
```
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
name: bgp-peer1v4
namespace: metallb-system
spec:
disableMP: false
holdTime: 0s
keepaliveTime: 0s
myASN: 64500
password: bgp-test
passwordSecret: {}
peerASN: 64500
peerAddress: 10.46.186.88
peerPort: 179
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
annotations:
metallb.universe.tf/address-pool: address-pools1
name: address-pools1
namespace: metallb-system
spec:
addresses:
- |
4.4.4.100 - 4.4.4.101
autoAssign: true
avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
name: bgpadvertisement
namespace: metallb-system
spec:
aggregationLength: 32
aggregationLengthV6: 128
communities:
- 500:500
ipAddressPools:
- …
```
=>  ffr-k8s: Make sure no duplicates prefix are passed to backend

internal/k8s/webhooks/webhookv1beta1/bfdprofile_webhook.go, internal/k8s/webhooks/webhookv1beta1/bgpadvertisement_webhook.go, internal/k8s/webhooks/webhookv1beta1/community_webhook.go, internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook.go, internal/k8s/webhooks/webhookv1beta1/l2advertisement_webhook.go, internal/k8s/webhooks/webhookv1beta2/bgppeer_webhook.go
Updates of Commonity resources were met with:
```
admission webhook "communityvalidationwebhook.metallb.io" denied the request without explanation
```
The reason being we had an empty return in the community update path. Here we remove it + the named returns that allowed it to align the rest of the paths.
/kind bug
Fixes https://github.com/metallb/metallb/issues/2597
```release-note
Fixed Community resources updates being denied without explanation.
```
=> Webhooks: fix Community update

website/content/concepts/_index.md
>
> /kind bug
> /kind design
> /kind flake
We moved from a behavior where the configuration was stale if the ips were still used to a behavior where we reconcile the service with the available ips. Here we clarify (hopefully) it in the docs.
Fixes https://github.com/metallb/metallb/issues/2449
```release-note
NONE
```
=> Docs: document the ip reconciliation behavior

.github/workflows/ci.yaml
The linked issue was closed, so we can re-enable the e2es.
/kind cleanup
```release-note
NONE
```
=> CI: Re-enable L2ServiceStatus e2es

internal/config/validation.go, internal/config/validation_test.go
>
/kind bug
> /kind design
> /kind flake
We can have l2 ipv6 addresses when using metallb in native mode. The important thing to consider is, not having any v6 based pool selected by a bgp advertisement. Here we narrow down the scope of the checking function.
Fixes https://github.com/metallb/metallb/issues/2431
```release-note
BGP native mode: narrow down the validation so that ipv6 pools are not valid only if there is a bgp advertisement referencing them.
```
=> IPV6 bgp validation: validate bgpadvertisement selected pools

website/content/configuration/_advanced_ipaddresspool_configuration.md, website/content/usage/_index.md, website/content/usage/example.md
Today's release notes for v0.14.9 state `The annotation prefix “metallb.universe.tf” is deprecated`, but the website doesn't reflect this and still references `metallb.universe.tf`. This PR should address this.
```release-note
docs: replace deprecated metallb.universe.tf annotation prefix with metallb.io
```
=> docs: replace deprecated metallb.universe.tf annotation prefix with metallb.io

e2etest/pkg/container/routes.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
I use this function from a test in frr-k8s that does not need to be interface agnostic
```release-note
NONE
```
=> E2E: make interface optional when fetching routes

tasks.py
/kind bug
>
> /kind bug
> /kind design
> /kind flake
The --short flag is not supported by recent kubectl clients, so the version is not reported, and kubectl is fetched even if it is already on the filesystem.
Although kubectl exits with a non-zero status, this is not caught by the get_command_version function.
```release-note
NONE
```
=> build: Fetch kubectl only if it is not present

website/content/metallb.md, website/layouts/_default/vanityurl.html
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
As part of the process of moving from metallb.universe.tf to metallb.io, we'd have to rename the package.
In order to do so, a vanity url page must be implemented to refer metallb.io/metallb to the actual repo.
Note: this could made parametric, and it will probably make sense to do so if we need vanity urls for frr-k8s and / or a separated test repo.
```release-note
NONE
```
=> Add redirect for the metallb.io/metallb vanity url

website/content/installation/clouds.md
>
> /kind bug
> /kind design
> /kind flake
The documentation explains how to enable the service account in case MetalLB was deployed via the manifests, but not via the Helm Charts.
```release-note
Docs: clarify how to install on Openshift via Helm.
```
Fixes https://github.com/metallb/metallb/issues/2422
=> Docs: specify the service account to use on OCP / helm

controller/main.go, e2etest/bgptests/bgp.go, e2etest/l2tests/assignment.go, e2etest/pkg/service/create.go, internal/allocator/allocator.go
>
/kind bug
> /kind design
> /kind flake
If the sharing criteria (ETP, endpoint selector) of a given service change, it might mean that the IP can be shared with other services.
Because of this,  we reprocess all the services.
```release-note
Reprocess the services and reassign IPs if the sharing criteria of a given service changes (ie, the external traffic policy changes and suddenly another service in pending becomes compatible).
```
Fixes https://github.com/metallb/metallb/issues/2403
=> Reprocess services if shareability of a given service changes

internal/config/validation.go, internal/config/validation_test.go
The commit extends the webhook validation to ensure BGPPeer resources with the interface field set are being validated as previously the .address was. When  Unnumbered BGP, the address field can be empty.
>
/kind bug
> /kind design
> /kind flake
```release-note
NONE
```
=> fix: webhook to handle interface field of BGPPeer resource

.github/workflows/publish.yaml
/kind feature
Publish the `metallb` helm chart to the `quay.io` oci registry
Fixes #2296 
```release-note
Publish charts to quay, along side existing publishing methods.
```
=> feat(oci): publish chart to quay registry

charts/metallb/templates/speaker.yaml, config/frr/frr-cm.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml
>
/kind bug
> /kind design
> /kind flake
Following frr's logs advice:
FD Limit set: 1073741816 is stupidly large. Is this what you intended? Consider using --limit-fds also limiting size to 100000
This should have a good effect on virtual memory size occupation, putting a limit instead of defaulting to the ulimit value.
Fixes https://github.com/metallb/metallb/issues/2584
```release-note
Limit the frr processes' file descriptors limit to 100000 instead of defaulting to host's ulimit value.
```
=> FRR mode: put a limit to the number of open file descriptors

controller/controller_test.go, controller/service.go, internal/allocator/allocation.go
>
/kind bug
> /kind design
> /kind flake
There is no point in adding a dual stack loadbalancer ip if the cluster ip is single family.
Additionally, when they do not match we feel free to clean the service and reassign:
https://github.com/metallb/metallb/blob/v0.14.9/controller/service.go#L109
which might cause an active service to change its ip.
Fixes https://github.com/metallb/metallb/issues/2724 and https://github.com/metallb/metallb/issues/2723
```release-note
Even if the service is prefer dual stack and dual stack pools …
```
=> IP Assignement: match clusterip family in case of single stack clusterip

ADOPTERS.md
This extends the list of adopters with the Kiratech Training project, where MetalLB is used as the reference technology in every lab that requires a Load Balancer. MetalLB is essential to several of our exercises, and every student learns how it works and the benefits of using this technology in (but not limited to) bare metal environments.
```release-note
NONE
```
=> Add Kiratech Training as an adopter

charts/metallb/README.md, charts/metallb/templates/prometheusrules.yaml, charts/metallb/values.yaml
We have some alerts that don't make sense for pools that have `autoAssign: false`, so we add a general way to exclude pools from triggering the relevant alerts.
Fixes https://github.com/metallb/metallb/issues/2665
/kind feature
```release-note
helm: Add option to exclude pools from triggering the relevant prometheus alerts
```
=> Helm: add option to exclude pools from triggering alerts

e2etest/webhookstests/webhooks.go, internal/config/config.go, internal/k8s/nodes/nodes.go, internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook.go, internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook_test.go
>
/kind bug
> /kind design
> /kind flake
This reverts commit 2e27f1c879c2ee1f3a16f29b8633b24ae98f10cd.
IP ranges specified as start-from and not as cidrs are not evaluated properly.
Fixes https://github.com/metallb/metallb/issues/2779
```release-note
Revert refusing ips overlapping with node cidrs as ip ranges are not handled correctly.
```
=> Revert "Detect and reject configurations where the service IP range overlaps with node IPs

.golangci.yml, controller/controller_test.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/k8s/controllers/bgp_status_controller.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/frrk8s_config_controller.go, internal/k8s/controllers/layer2_status_controller.go, internal/k8s/controllers/node_controller.go, internal/k8s/controllers/pool_controller.go, internal/k8s/controllers/pool_status_controller.go, internal/k8s/controllers/service_controller.go, internal/k8s/controllers/service_controller_reload.go, speaker/main.go, tasks.py
/kind cleanup
This bumps `golangci-lint` to the latest v2 release to take advantage of updated linters and converts the config file to use the new config format. Addresses any lints that come along with latest release(s)
N/A
<!--  Write your release note:
```release-note
NONE
```
=> bump golangci-lint to v2

charts/metallb/templates/controller.yaml, charts/metallb/templates/networkpolicy.yaml, e2etest/netpoltests/networkpolicies.go
/kind cleanup
There is an obvious bug for networkpolicies that should exist when not disabled.
Refactor the networkpolicies test to be able to run when deployed by operator
```release-note
NONE
```
=> Handle better the webhook mode

charts/metallb/README.md, charts/metallb/templates/speaker.yaml, charts/metallb/values.schema.json, charts/metallb/values.yaml
This provides some value, and makes scanners happier.
Fixes [2774](https://github.com/metallb/metallb/issues/2774)
/kind bug
```release-note
helm charts: add option to specify init container resources
```
=> charts: add option to specify init container resources
