arp-speaker/main.go
bgp-speaker/main.go
internal/k8s/k8s.go

Make it public and call it from {bgp,arp}-speaker.
Fixes #29

Move nodeHasHealthyEndpoints to internal/k8s

---

AUTHORS

@miekg @xnaveira : please review and check if I'm crediting you correctly, or if you want to be credited some other way. Thanks!

Add Miek Gieben and Xavier Naveira to AUTHORS.

---

fabfile.py

This makes ```fab push:registry=some.non.local.registry``` work.

Add custom registry to fab push

---

manifests/metallb-arp.yaml

Add manifest for arp-speaker. This adds an RBAC role for the leader
election.

Add arp manifest

---

arp-speaker/main.go
internal/arp/arp.go

Actually set `ann` in controller and adds better errors and logging to
see what is going on.

arp-speaker: better logging and fixes

---

arp-speaker/main.go
internal/k8s/leader.go

I believe it was crashing because of the nil record.EventRecorder; doing
this properly(?) makes you chase about 5 structures that need to be
filled out. Took a shortcut by implementing the interface and nooping
the whole damn thing.
Fixes #57

Fix leadership code

---

internal/arp/arp.go
internal/arp/leader.go
internal/k8s/leader.go

* more logging
* send unsolicitated arps every 10 second
* make leader election times longer

arp-speaker: more logging and other fixes

---

dockerfiles/prod.tmpl
dockerfiles/prod/bgp-speaker
dockerfiles/prod/controller

Add required linux headers to the dockerfile build.

---

Makefile.inc
arp-speaker/Dockerfile
arp-speaker/Makefile
bgp-speaker/Dockerfile
bgp-speaker/Makefile
controller/Dockerfile
controller/Makefile

This PR has no commits other than adding Makefiles and Dockerfiles.

Dockerfile and Makefiles

---

manifests/arp-config.yaml

All BGP bits are not needed, add simple config

add arp-config

---

internal/arp/arp.go

Less spammy logging and add String() for dropReason.

arp-speaker: make logging less spammy

---

manifests/arp-config.yaml
manifests/example-config.yaml
speaker/arp_controller.go
speaker/bgp_controller.go

Update yaml for protocol changes

---

internal/arp/leader.go
speaker/arp_controller.go
speaker/bgp_controller.go

My LB still works, but the logs seem to contradict this.

Better protocol logging

---

internal/arp/leader.go
speaker/arp_controller.go
speaker/bgp_controller.go

This should be handled via monitoring; no need to spam the logs with
this.

arp: drop the sending unsolicitated logs

---

website/content/design.md
website/content/index.md
website/content/installation.md
website/content/tutorial.md

* s/bgp-speaker/speaker
* tell we do ARP
* fix tutorial

Website: cleanups for arp/bgp

---

internal/arp/arp.go
internal/arp/arp_test.go
internal/iface/iface.go
internal/ndp/ndp.go

Allows to mimimize the similarties between ARP and NDP. Also put
dropReasons and there and made them public.

Start new internal/iface package

---

manifests/example-config.yaml
website/content/configuration/romana.md

Documents how to run MetalLB alongside Romana, if you're using the route publisher addon. It requires some semi-tricky BGP configuration and has some subtle gotchas

Document how to integrate MetalLB and Romana

---

internal/arp/leader.go
internal/k8s/leader.go

Put all leadership state changes in leadership.go and double check
if we're really the leader when sending unsolicitated responses and in
various other places.

arp leadership: cosmetic changes

---

glide.lock
glide.yaml
vendor/github.com/mdlayher/ndp/conn.go
vendor/github.com/mdlayher/ndp/conn_test.go

Enables the NDP speaker to join the appropriate solicited node multicast groups.
Updates #83 
n/a

vendor: bump github.com/mdlayher/ndp

---

internal/config/config.go
internal/config/config_test.go

Adds configuration for NDP pools and some sanity checking for ARP and NDP.
Updates #83 
Also adds subtests so it's much easier to pick and run individual cases.

internal/config: support NDP pools, add tests

---

README.md

Update the maturity bage link since it 404's

README - fix maturity link

---

controller/controller_test.go
controller/service.go
internal/allocator/allocator_test.go
internal/config/config.go
internal/config/config_test.go
internal/layer2/stats.go
manifests/example-layer2-config.yaml
speaker/bgp_controller_test.go
speaker/main.go
website/content/concepts/_index.md
website/content/concepts/layer2.md
website/content/configuration/_index.md
website/content/release-notes/_index.md
website/content/tutorial/_index.md
website/content/tutorial/layer2.md
website/content/usage/_index.md

Rename ARP and NDP to Layer 2 throughout the code and documentation

---

internal/config/config.go
internal/config/config_test.go
manifests/example-config.yaml
website/content/configuration/_index.md

Understand ranges of IP addresses in config, in addition to CIDR prefixes.

---

manifests/example-config.yaml
website/content/installation/_index.md

Document the existence of the Helm package in installation instructions.

---

website/content/concepts/layer2.md

Make it more explicit that layer2 failover is autonomous.

---

internal/layer2/ndp.go

Failure to do so leads to goroutines spinning on as much CPU as k8s
is willing to give them.
Fixes #246

Correctly shut down NDP responders when interfaces go away.

---

internal/bgp/bgp.go
internal/bgp/messages.go
website/content/release-notes/_index.md

Don't send localpref across eBGP sessions.

---

website/content/community/_index.md

add minikube service test-bgp-router-ui -n metallb-system
remove GoBGP router from test-bgp-router 
Fixes #

Refine the COMMUNITY & CONTRIBUTING doc about test-bgp-router-ui

---

controller/controller_test.go
controller/service.go

Actually allow layer2 mode to use the Local traffic policy.

---

website/content/configuration/_index.md

Adds configmap declaration, fixes #285

---

internal/layer2/announcer.go
website/content/release-notes/_index.md

Fix gratuitous ARP and NDP announcements on IP failover.

---

internal/bgp/bgp.go

If changes some calls to syscall.Sock* to unix.Sock* which should have better support for ARM
**Which issue(s) this PR fixes**:
Fixes #289 
Untested, the Hacking guide was not working properly for me, so I've only been able to run basic Go tests, not the integration or E2E tests.

Use golang.org/x/sys/unix instead of basic syscall library

---

internal/layer2/announcer.go
speaker/main.go

BGP mode does its own "refcounting" through announcement deduplication.
Fixes #295

Move IP refcounting into the layer2 package.

---

website/content/tutorial/layer2.md

Update log message examples to current format

---

website/content/tutorial/minikube.md

10.96.0.102 is not used in the example

---

website/content/installation/network-addons.md

I've been using Cilium with MetalLB in BGP mode for about a week and no issues so far.

Add Cilium to list

---

internal/layer2/announcer.go

This PR disables listening on interfaces which have NOARP flag set.
**Which issue(s) this PR fixes** :
Fixes #351

Layer 2: do not listen on interfaces with NOARP flag

---

website/content/tutorial/minikube.md

Remove unnecessary 'a'

---

website/content/installation/network-addons.md

adding Canal to CNI compatibility matrix

---

Makefile

It fixes the CircleCI jobs failures
Fixes #374
This was the change in helm that caused the problem
https://github.com/helm/helm/pull/4883/files#diff-12ef33d707921b337089ac53ee08f538R96

Fix CircleCI failures

---

website/content/community/_index.md
website/content/faq/_index.md
website/content/release-notes/_index.md

Add an FAQ section to the docs to help with frequently asked questions and support.
Fixes #
I just picked some of the questions from the last few weeks in Slack, I am sure we can refine that FAQ over time.
I'm not a Hugo master so... I'm not sure if that's the right way to go about this :)

Add FAQ doc

---

website/content/concepts/_index.md
website/content/configuration/_index.md
website/content/faq/_index.md

issue](https://github.com/google/metallb/issues/new) first, and get
accepted.

Adding concept and configuration docs as well as a FAQ update

---

website/content/installation/_index.md

I've been able to make MetalLB work in OpenShift 4 and wrote about it here https://www.underkube.com/posts/metallb-on-ocp4-baremetal/
This PR just adds some notes on how to patch the current kubernetes manifests to make it work.
I was wondering if submit this PR or a PR to include a specific manifest file with the fixes, but I believe this is more educational.
Thanks!

Added steps to make it work in OpenShift 4

---

website/content/installation/_index.md

See https://github.com/danderson/metallb/blob/master/helm-chart/values.yaml#L20

Fixed helm chart configInline ref

---

internal/config/config.go

Logged detailed error in case of CIDR parsing failure.

Fixed #481: Added detailed error in case of CIDR parsing failure.

---

internal/config/config.go
internal/config/config_test.go

feat(config): allow spaces in IP ranges

---

internal/allocator/allocator.go

- Fixed the bug described in https://github.com/danderson/metallb/issues/147#issuecomment-410614084 .
- Remove an unnecessary assignment.

Fix to expose addresses_total metrics

---

website/content/installation/_index.md

This PR describes https://github.com/danderson/metallb/issues/153#issuecomment-518651132 in installation steps

Add strict ARP enabling note 

---

website/content/installation/clouds.md

issue](https://github.com/google/metallb/issues/new) first, and get
accepted.

Update Hetzner support in clouds.md

---

website/content/installation/_index.md

Fix create secret snippet

---

website/content/installation/_index.md

Will hopefully save the next person who wants to automate deployment
in an idempotent way some time.

expand install docs how to easily automate strictARP change

---

website/content/installation/_index.md

Quick grammatical tweak

---

website/content/installation/_index.md

... done
issue](https://github.com/google/metallb/issues/new) first, and get
accepted.
... trivial
... not a bug

update install website to set kustomize ref to v0.9.3 - sync with metallb version

---

website/content/installation/_index.md

Supersedes #583. Opened a new PR as I can't push changes to the old one.
I've incorporated the feedback from the old PR and improved the phrasing a bit. Comments are welcome.

Website: Add upgrade information

---

dev-env/README.md
dev-env/bgp/README.md
tasks.py

This PR fixes some nitpicks related to the dev environment documentation.

Clean up dev-env documentation

---

tasks.py

To make dev-env support a bit easier, enforce a minimum kind version
known to be working.  The bgp support in particular expects >= 0.8, but
this patch enforces the version for all dev-env usage.
If you run `inv dev-env` with kind 0.7.0, for example, the output would
be:
```
kind version
kind v0.7.0 go1.13.6 linux/amd64
kind version >= 0.8 required
```
Closes #711

dev-env: Validate minimum kind version

---

website/content/installation/clouds.md

Tagging you as reviewers mostly as an FYI, as I think this change doesn't really need any reviews. I'll directly merge (I've tested it locally)
If you have something to change, please let me know and I'll fix it in a following PR :)
The link to github.com/packet-labs is not changed as that repo doesn't seem to have any redirects

docs: Rename Packet to Equinix Metal

---

website/content/installation/clouds.md

I broke the alphabetical order in the previous commit, this fixes it :see_no_evil:

website: Keep clouds table in alphabetical order

---

website/content/_index.md

Fixes https://github.com/metallb/metallb/issues/782

Mention firewall requirement for Layer 2

---

website/content/usage/example.md

Update example configuration file to use the current format, `communities` section has been renamed to `bgp-communities`.

docs: Update configuration file example

---

website/content/configuration/k3s.md

Hi.
Just documenting a minor issue with k3s.
Checked it with local (0.32.1) Hugo.
Thanks.

Document issue with MetalLB on K3s

---

website/content/community/code-of-conduct.md

website: Update contacts for code of conduct

---

speaker/main.go

Do not log startUpdate/endUpdate for non LoadBalancer services

---

.circleci/config.yml
tasks.py
website/content/community/_index.md

I've received comments on a couple of PRs recently about putting 2
spaces after a period.  This patch will get CI to flag this
automatically.  It also puts the check in an easy command to run
locally, "inv checkpatch", which can be extended for other patch style
checking.

ci: Check for 2 spaces after a period

---

controller/main.go
internal/k8s/k8s.go
internal/speakerlist/speakerlist.go
manifests/metallb.yaml
speaker/main.go
tasks.py
website/content/installation/_index.md
website/content/release-notes/_index.md

We name the role secret-updater as the controller will
rotate the secret at some point

Make the controller create memberlist secret

---

.github/workflows/release-chart.yaml

Only release on tags that match v*

chart: only trigger chart-releaser-action on release tags

---

ct.yaml

The version will be increased when a release is done

helm lint: disable CheckVersionIncrement

---

website/content/community/release-process.md

Add steps to cherry-pick a commit

---

tasks.py

Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
If dev clusters are created with a different name the dev-env-cleanup task cannot clean them up.

tasks: Add name parameter to dev-env-cleanup

---

e2etest/bgp_test.go
e2etest/layer2_test.go
tasks.py

This PR fixes a failure in the e2etest and also fixes a bug that caused the failure to silently pass the CI.

e2etest: Fix CI failure

---

tasks.py

Being able to specify the image to use for the node allows us to create
test cluster pinned to specific kind versions.

Add an optional kind node image parameter to dev-env

---

charts/metallb/templates/psp.yaml
charts/metallb/templates/rbac.yaml

Fixes #878
Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>

Ensure RBAC for Helm matches YAML manifests

---

website/content/installation/_index.md

website: Fix wrong markdown in installation page

---

internal/layer2/announcer.go

Fixes #745
(tested on 1.19.10 cluster / CentOS 8)

layer2: stop spamLoop() ticker when not used

---

website/content/_index.md
website/content/concepts/_index.md
website/content/concepts/bgp.md
website/content/concepts/layer2.md
website/content/concepts/maturity.md
website/content/configuration/_index.md
website/content/installation/_index.md
website/content/installation/clouds.md
website/content/release-notes/_index.md
website/content/usage/_index.md

doc: mostly load-balancer to load balancer

---

.golangci.yml
internal/allocator/allocator_test.go
internal/bgp/bgp.go
internal/k8s/endpoint_slices.go
internal/k8s/k8s.go
internal/logging/logging.go
internal/speakerlist/log.go

This PR adds linter rules for enforcing comment style.

Enforce comment style

---

commitlint.config.cjs

This prevent the use of Signed-off-by
fixes #918

Do not enforce that body ends with a period

---

website/content/community/_index.md

website: Drop IRC from community page

---

charts/metallb/templates/speaker.yaml
charts/metallb/values.schema.json
charts/metallb/values.yaml

Modifies template to add runtimeClassName variable interpolation.

Add runtimeClassName support to speaker template

---

e2etest/bgp_test.go
e2etest/pkg/metrics/metrics.go

Instead of assuming that the metrics port is 7472 it
now scrapes all monitoring ports of a given pod.
In addition, since multiple containers in a pod can
expose the same metric name, ForPod now returns a slice
of metrics map, each map corresponding to a container.

Refactor metrics test to scrape all monitoring ports

---

e2etest/bgp_test.go
e2etest/pkg/frr/config/config.go
internal/bgp/frr/config.go
internal/bgp/frr/docker_test.go
internal/bgp/frr/frr.go
internal/bgp/frr/testdata/TestSingleAdvertisement.golden
internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden
internal/bgp/frr/testdata/TestSingleAdvertisementInvalid.golden
internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden
internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden
internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden
internal/bgp/frr/testdata/TestSingleSession.golden
internal/bgp/frr/testdata/TestSingleSessionClose.golden
internal/bgp/frr/testdata/TestTwoAdvertisements.golden
internal/bgp/frr/testdata/TestTwoSessions.golden
internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden
internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
manifests/metallb-frr.yaml

This PR add the following config options to FRR template and update UT
- logging to file
- holdtimer settings
- md5 authentication password
- update source settings
- bgp multiple view support

Additional FRR configurations options

---

e2etest/bgp_test.go
tasks.py

This is a subset of the commits in https://github.com/metallb/metallb/pull/1012 to make review easier and to try to de-flake the CI:
- make the test timeout longer
- have the gauge check inside an eventually loop
The gauge is the most common flake

E2E improvements

---

e2etest/layer2_test.go

It may take some time to have the event we check available, here instead of checking once, we check inside an eventually loop to avoid flakes.

E2E test: make the check for sharing ip l2 test in eventually

---

website/content/community/maintainers.md

I've opened a PR to add fede to the CNCF/foundation repo: https://github.com/cncf/foundation/pull/258/files
And asked him to do the other steps I document in this PR.
Closes: #994

Document the CNCF steps to add new maintainers

---

e2etest/bgp_test.go

https://github.com/metallb/metallb/pull/1032 was merged before rebase, breaking the e2e tests. This fixes the compilation errors.

Fix not compiling e2e tests

---

e2etest/bgp_test.go
e2etest/pkg/frr/bgp.go
internal/bgp/frr/config.go
internal/bgp/frr/frr.go
internal/bgp/frr/frr_test.go
internal/bgp/frr/testdata/TestSingleAdvertisement.golden
internal/bgp/frr/testdata/TestTwoAdvertisements.golden
internal/config/config.go

FRR template lacking ability to update bgp advertisment community, This PR extend the template 
to add the additional support and unit-test

Use bgp-communities to update BGP community advertisements with FRR

---

e2etest/layer2_test.go

Since we're creating multiple pods, the announcing
speaker can change until all the pods are ready and
the situation is stabilized.
Adding a 5 seconds sleep should be enough for the
speakers to settle on who announces the service,
and should be enough for it to complete sending the
gratuitous ARPs as that's the time set in spamLoop().
This should solve the flake we're experiencing recently in the CI.

Let speakers settle in L2 ExternalTrafficPolicy=Local tests 

---

e2etest/bgp_test.go
e2etest/pkg/frr/bgp.go
internal/bgp/frr/config.go
internal/bgp/frr/frr.go
internal/bgp/frr/frr_test.go
internal/bgp/frr/parse.go
internal/bgp/frr/testdata/TestSingleAdvertisement.golden

BGP Advertisement configuration API allow setting LOCAL_PREF, this PR
extend FRR configuration template to propagate this configuration to FRR

Add set local-preference route-map action to frr config

---

.github/workflows/ci.yaml

We have helm lanes on circleci, we want to make gh actions on par so we can shut down circleci.

Add helm lanes to github actions

---

e2etest/pkg/config/update.go

The keepalive parameter was missing, making the tests fail when setting it.

E2E Operator Mode: add keepalive time to the conversion

---

internal/bgp/frr/config.go
internal/bgp/frr/frr.go

Using maps to render the template works but has one drawback. When
iterating over maps, frr does not guarantee order.
This has two major drawbacks: the unit tests with goldenfile are not
stable, but more importantly, we risk to produce different rendering
from the same config, causing un-necessary reloads.
Here we still use maps (and sets) to guarantee there are no
duplicates, but before rendering we convert the map to a sorted slice
to make the output stable.

Convert maps to sorted slices for prefixes

---

e2etest/pkg/metallb/metallb.go

In some deployments it's possible to have a different speaker / controller label selector. Here we add a way to override them in tests so we can run e2e against those deployments.

E2E: override the speaker / controller selector

---

website/content/configuration/troubleshooting.md

Added details to the troubleshooting page I learned during a debugging session with @fedepaol.

Troubleshooting: Add details about ping and arping

---

website/content/_index.md

as discussed on slack: https://kubernetes.slack.com/archives/C8FSTGU56/p1643786811893069

update requirements: memberlist only needed for l2

---

e2etest/l2tests/l2.go

In this test sometimes we get the wrong node when looking for the advertising node of a service.
A newly created service can get the same IP the service from the previous test got (since it was already deleted).
While the previous service is down it can take time for the running host ARP table to be updated.
The solution for such situation is to look for the advertising node of a service inside an eventually.
Fixing issue https://github.com/metallb/metallb/issues/1195.
An example of the failing test can be found here:
https://github.com/metallb/metallb/runs/4911555260?check_suite_focus=true

L2 E2E tests: Flake fix: metrics validation of wrong speaker 

---

website/content/community/maintainers.md

This shouldn't be an item on the list, just a new paragraph

website: Fix typo in maintainers doc

---

e2etest/bgptests/bgp.go
e2etest/pkg/config/parse.go
go.mod
internal/bgp/frr/frr_bfd_test.go
internal/config/config_test.go
internal/pointer/pointer.go
speaker/bgp_controller_test.go
speaker/layer2_controller_test.go

Many implementations of the same function were scattered across different test packages. Here we collect all of them in a package and use it.

Refactor uint32ptr / boolptr in a package

---

api/v1beta1/community_webhook.go
api/v1beta1/community_webhook_test.go
api/v1beta1/mock_validator_test.go
charts/metallb/templates/webhooks.yaml
config/manifests/metallb-frr-with-webhooks.yaml
config/manifests/metallb-native-with-webhooks.yaml
config/webhook/manifests.yaml
e2etest/webhookstests/webhooks.go
internal/config/validator.go
internal/k8s/k8s.go

This PR adds the webhook for the Community CRD.
Based on the Add Community CRD PR #1253

Add Community Webhook

---

website/content/configuration/calico.md

Starting with v3.18, Calico can now work with MetalLB (or other load
balancers) to announce LB IP blocks via Calico's BGP code.
There's limited configurability this way, but works for my sample
case.  I've left most of the workarounds in the doc, but documented
the simple case first.

Update calico.md to cover Calico v3.18+ support

---

e2etest/bgptests/bgp.go

As part of an existing test, added a check for the
functionality of assigning ip without announcing.

E2E: add test assign ip only

---

go.mod
internal/config/config.go
internal/k8s/controllers/config_controller_test.go
internal/k8s/controllers/fakeclient_test.go
internal/k8s/controllers/node_controller_test.go
internal/k8s/controllers/pool_controller_test.go
internal/k8s/controllers/service_controller_test.go

Adding unit tests to cover the controllers.

Add controllers unit tests

---

internal/config/config.go

This commit separates the logic of creating the Config
struct in the For function into 3 different functions.

Refactor Config.For function

---

CODEOWNERS

Adding Ori and Graeme as maintainers

Add Ori and Graeme as maintainers

---

e2etest/bgptests/bgppeer_selector.go
e2etest/pkg/frr/bgp.go

Adding more tests is not a bad idea, and dual-stack
scenarios might be more sensitive to future frr.conf refactors

E2E: BGP peer selector dual-stack tests

---

.github/workflows/ci.yaml

Restore the operator lane, aligned to metallb without certmanager.

Bump the operator version

---

controller/main.go

We want to be able to deploy the controller as standalone backend for
the webhook. Also, for such deployments we want the "real" controller
not to act as webhook, so we add a webhook mode parameter to enable,
disable or run only in webhook mode.

Add webhook mode

---

website/content/release-notes/_index.md

Add the release notes for the upcoming version.

Release notes 0.13.0

---

website/content/community/release-process.md
website/content/configuration/_index.md

Removing the helm release notes, and adding a note about bad configuration handling.

Minor doc updates

---

website/content/release-notes/_index.md

Adding the awesome people that made 0.13.0 possible!

Release notes: add the contributors to 0.13.0

---

.github/workflows/publish.yaml

Aligning 0.13 with the fix on main

Publish job: change the branch / tag selector

---

website/content/configuration/_index.md

Fixing the broken links to relative configuration sections.
Fixes https://github.com/metallb/metallb/issues/1489

Docs: fix broken configuration links

---

website/content/release-notes/_index.md

Extend the release notes with the 0.13.5 content.

Release notes: prepare 0.13.5

---

configmaptocrs/main.go

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>
https://github.com/metallb/metallb/runs/8206972097?check_suite_focus=true

fix potential CI failure since loop Map is out of order

---

e2etest/l2tests/interface_selector.go

This PR adds more e2etest about L2 interface selector.

E2etest: add more L2 interface selector e2etest

---

website/content/configuration/_advanced_l2_configuration.md
website/content/release-notes/_index.md

Release notes: Add a feature description to 0.13.6

Release notes: Add a feature description to 0.13.6

---

website/content/configuration/_advanced_bgp_configuration.md
website/content/configuration/_advanced_l2_configuration.md

This PR adds namespace configuration for the example resources where it was missing.

Documentation: added missing namespaces

---

.github/workflows/stale.yaml

Adds initial configurations for a stalebot workflow.
Some tuning required which will be expected in the conversation for this PR.
resolves #1426

Add initial configuration for stalebot

---

.github/workflows/publish.yaml

Fixes issue in current publishing pipeline that appears to be fixed in the latest version of cosign
https://github.com/sigstore/cosign/issues/2390#issuecomment-1293576146
Fixes #1676

Bump cosign version

---

CODEOWNERS

Moving myself to emeritus maintainer status. Keep up the good work, folks! 👋

Move johananl to emeritus maintainer list

---

charts/metallb/README.md
charts/metallb/policy/speaker.rego
charts/metallb/templates/speaker.yaml
charts/metallb/values.schema.json
charts/metallb/values.yaml
config/controllers/speaker.yaml
config/manifests/metallb-frr-prometheus.yaml
config/manifests/metallb-frr.yaml
config/manifests/metallb-native-prometheus.yaml
config/manifests/metallb-native.yaml
internal/k8s/k8s.go
speaker/main.go

This PR changes the way we insert the memberlist secret key to the speaker.
Switching from env var to a file in volume mount.

Use file volume mount for memberlist secret key

---

.github/workflows/ci.yaml
configmaptocrs/main.go
frr-metrics/collector/bfd.go
frr-metrics/collector/bfd_test.go
frr-metrics/collector/bgp.go
frr-metrics/collector/bgp_test.go
frr-metrics/collector/vtysh.go
frr-metrics/exporter.go
internal/bgp/frr/config.go
internal/bgp/native/native.go
internal/config/config.go
internal/k8s/controllers/service_controller_reload.go
internal/k8s/k8s.go
internal/logging/logging.go

I've added gosec to the CI job
then went over the results and fixed all the high/medium issues.
for now, I've left LOW out of scanner result as this seems to include too many false positives and the benefit from investing in these is .. low..
this fixes #1712

Introduce gosec as Static Code Analysis tool

---

e2etest/bgptests/infra_setup.go
e2etest/bgptests/vrf.go
internal/config/validation.go
internal/config/validation_test.go

When using VRFs it's allowed to have different asns per vrf.

Allow to have different ASNs per VRF on metallb side

---

e2etest/l2tests/assignment.go

While creating test ip pool for test namespace by referring to its f.Namespace.Labels, then it contains old labels due to race condition which causes ip pool never get used for service as intended and makes test to fail. Hence this retrives latest namespace object and using some of its labels for the pool creation.

Fix l2 ip pool assignment test

---

e2etest/bgptests/infra_setup.go

When we clear, we need to understand if the multihop container is running, because otherwise we'll panic in inspecting it (and in removing the multihop wiring). Checking the error depends on the container runtime, so it's a poor choice. Here we check if the container is among those we are processing, and if not we don't tear down the multihop setup.

Make the exit more robust

---

.github/workflows/vulncheck.yaml

Adding the action to asses vulnerabilities with govulncheck.

Add govulncheck action

---

.github/workflows/ci.yaml
.github/workflows/vulncheck_periodic.yaml

Fixing so that the job can write the security events.
Also, change the scheduling to every 6 hours.

Fix vulncheck permissions

---

website/content/release-notes/_index.md

Prepare the 0.13.8 release notes

---

configsamples/bgppeer_with_vrf.yaml
website/content/configuration/_advanced_bgp_configuration.md

Updating the docs and adding an example.

Docs: add notes about VRFs

---

internal/layer2/arp.go
internal/layer2/ndp.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error

Use errors.Is to check for a specific error

---

api/v1beta1/bgppeer_conversion.go
configmaptocrs/main.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
An nil error returned in a function that added a useless judgment when called. This pr optimization parameter returns a value defined

Clean up nil error returns for the functions

---

.golangci.yml
e2etest/bgptests/node_selector.go
internal/config/config_test.go

enable gofmt linters and improve code format

---

e2etest/bgptests/bgp.go
e2etest/l2tests/l2.go
e2etest/pkg/k8s/nodes.go
internal/k8s/controllers/node_controller.go
internal/k8s/controllers/node_controller_test.go
internal/k8s/k8s.go
internal/k8s/nodes/nodes.go
speaker/bgp_controller.go
speaker/bgp_controller_test.go
speaker/layer2_controller.go
speaker/layer2_controller_test.go
speaker/main.go
speaker/speaker_test.go

This PR fixes the bug of MetalLB ignoring the node NetworkUnavailable condition and adds/updates
relevant unit tests and e2e tests.
fixes #1710

Respect network unavailable condition

---

e2etest/l2tests/assignment.go

This test verifies that the watch on namespaces in the controller
triggers when the labels of a namespace is modified.

Add assignment test triggered by a namespace update

---

tasks.py

When doing the release process, the sidecar containers *-cp were not being tagged properly, with the result of having the kustomize - manifests based deployment using the "main" tag.
Here we fix and we change the bumprelease command to verify we didn't leave any :main tag around.

Release: override the tag of the copy init containers

---

website/content/prometheus-metrics/_index.md

add allocator addresses metrics to docs

---

website/content/configuration/_advanced_ipaddresspool_configuration.md

Rephrase docs about `IPAddressPool` priority

---

charts/metallb/README.md
charts/metallb/values.yaml
config/frr/speaker-patch.yaml
config/manifests/metallb-frr-prometheus.yaml
config/manifests/metallb-frr.yaml
e2etest/e2etest_suite_test.go
internal/bgp/frr/docker_test.go
tasks.py

update frr to 8.5.2

---

controller/controller_test.go
controller/service.go

make annotations: metallb.universe.tf/address-pool, metallb.universe.tf/loadBalancerIPs,metallb.universe.tf/ip-allocated-from-pool public, it's good for external clients.
Fixed https://github.com/metallb/metallb/issues/2027

make some well-known annotations public

---

README.md

Fix CI status badge in main README

---

.github/workflows/cifuzz.yml

Add [Cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow for PR Fuzzing.

[Fuzzing] add cifuzz support

---

config/frr-k8s/kustomization.yaml
config/manifests/metallb-frr-k8s.yaml

main is a moving target, we want to pin to a stable version.

Kustomize: pin the frr-k8s overlay to 0.0.1

---

tasks.py

Change to reflect network inspect output in podman v4: https://docs.podman.io/en/v3.4.4/markdown/podman-network-inspect.1.html https://docs.podman.io/en/v4.0.0/markdown/podman-network-inspect.1.html

tasks: Fix podman network inspect

---

website/content/_index.md
website/content/concepts/maturity.md

Providing a better description of the maturity.

Docs: align the maturity description to the current status

---

website/content/release-notes/_index.md

Prepare the 0.14.0 release notes

---

charts/metallb/README.md
charts/metallb/values.yaml
config/frr/speaker-patch.yaml
config/manifests/metallb-frr-prometheus.yaml
config/manifests/metallb-frr.yaml
e2etest/e2etest_suite_test.go
internal/bgp/frr/docker_test.go
tasks.py
website/content/release-notes/_index.md

This would allow FRR to peer with localhost, among others.
Fixes https://github.com/metallb/metallb/issues/2256

Bump FRR to 9.0.2

---

design/0001-frr.md
design/speaker.md

Fix typos in the design document

---

README.md

**Is this a BUG FIX or a FEATURE ?**: /kind feature
related #2294
Add a reminder in `https://metallb.github.io/metallb`
Preview:
```release-note
NONE
```

Add helm chart repository page

---

.github/workflows/publish.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Bumping cosign as we are hitting 
https://github.com/sigstore/cosign/issues/3614
```release-note
NONE
```

Bump cosign

---

.github/workflows/publish.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```

Cosign: add the --yes flag to skip prompts

---

website/gen_relnotes.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Generating the list of contributors based on from-to to make it easier to generate the release notes.
```release-note
NONE
```

Release notes generator: provide the list of contributors

---

e2etest/pkg/frr/bgp.go
internal/bgp/frr/config.go
internal/k8s/webhooks/webhookv1beta1/l2advertisement_webhook.go

chore: fix function names in comment

---

website/content/concepts/bgp.md

This is a minor spelling fix for documentation.
N/A
```release-note
NONE
```

Minor spelling fix for bgp.md

---

.github/workflows/ci.yaml
internal/bgp/frr/config.go
internal/bgp/frr/frr.go
internal/bgp/native/messages.go
internal/bgp/native/native.go
internal/safeconvert/convert.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixing the gosec errors. 
Also, instead of relying on master, we pin it so we'll have less background noise and more control of what failed when bumping (I hope!).
```release-note
NONE
```

Fix gosec warnings and pin gosec version

---

.github/workflows/ci.yaml
.github/workflows/vulncheck_periodic.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Let's switch to the officially released one.
```release-note
NONE
```

Use the official govulncheck gh action

---

e2etest/pkg/executor/executor.go

/kind flake
#2526 
```release-note ```
```
NONE
```

E2E: ignore stderr if error is nil when kubectl exec

---

.github/workflows/publish.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Bumping the gh actions used to publish.
```release-note
NONE
```

Publish jobs: bump gh actions

---

speaker/layer2_controller.go

Added debug log. The lack of logs in this case makes troubleshooting impossible in case a pod is scheduled
Fixed #2505 
/kind cleanup
Improve debugging
```release-note
Add debug log when a speaker is not announcing because of network unavailable / exclude from loadbalancer annotation.
```

Add log for L2 speaker when node is not usable

---

api/v1beta2/bgppeer_types.go
charts/metallb/charts/crds/templates/crds.yaml
config/crd/bases/metallb.io_bgppeers.yaml
config/manifests/metallb-frr-k8s-prometheus.yaml
config/manifests/metallb-frr-k8s.yaml
config/manifests/metallb-frr-prometheus.yaml
config/manifests/metallb-frr.yaml
config/manifests/metallb-native-prometheus.yaml
config/manifests/metallb-native.yaml
design/gracefulrestart-bgp.md
website/content/apis/_index.md
website/content/configuration/_advanced_bgp_configuration.md

Fixes #2531
```release-note
Help section for BGP Graceful Restart feature added
```

Doc: add BGP graceful restart section in the website

---

e2etest/l2tests/assignment.go

The test verifies that a service (svc) assigned to a dual-stack pool correctly switches to a new dual-stack pool when its original pool is replaced by a single-stack pool. Previously, the test used `Eventually` to assert that the svc maintained 2 IPs, which caused flakiness since the svc could still hold old IPs temporarily.
To fix this, the test now also verifies that the svc's IPs are different from the original ones, ensuring a proper pool switch before final IP count validation. This prevents premature test completion and ensures accurate reassignment detection.
>
> /kind bug
> /kind design
/kind flake
**What …

Fix(tests): resolve flakiness in service pool reassignment test

---

website/content/troubleshooting/_index.md

>
> /kind bug
> /kind design
> /kind flake
RPF is a possible cause of issues with metallb. Here we mentioni it in the troubleshooting guide.
```release-note
NONE
```
Fixes https://github.com/metallb/metallb/issues/297

Website: mention RPF in the metallb troubleshooting guide

---

tasks.py

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Instead of relying with what's on the server, we fetch the ginkgo version corresponding to what we have defined in go.mod.
```release-note
NONE
```

tasks: use local ginkgo

---

CODEOWNERS
README.md

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Moving them after a long period of inactivity.
Thanks for the help on the project!
cc @russellb @gclawes 
```release-note
NONE
```

Move russell and graeme to emeritus maintainers

---

netlify.toml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Redirecting the url, as now the official home is metallb.io
Fixes https://github.com/metallb/metallb/issues/2391
```release-note
NONE
```

Website: set redirects for metallb.universe.tf to metallb.io

---

configmaptocrs/Dockerfile
controller/Dockerfile
e2etest/go.mod
e2etest/go.work
e2etest/go.work.sum
go.mod
speaker/Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```

chore: update go toolchain to 1.22.11

---

configmaptocrs/Dockerfile
controller/Dockerfile
e2etest/go.mod
e2etest/go.work
go.mod
speaker/Dockerfile

Using the latest go, fixing some cves.
/kind cleanup
```release-note
NONE
```

Use latest 1.22 go

---

tasks.py

/kind bug
>
> /kind bug
> /kind design
> /kind flake
Without yq, "inv generatemanifests" fails:
```shell
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
[--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
[--indentless-lists] [--explicit-start] [--explicit-end]
[--in-place] [--version]
[jq_filter] [files ...]
yq: error: argument files: can't open 'select(.kind == "CustomResourceDefinition")': [Errno 2] No such file or directo
ry: 'select(.kind == "CustomResourceDefinition")'
```
CI has been working because yq is installed on the GitHub Actions runners. See …

build: Install yq, required to generate manifests

---

e2etest/bgptests/unnummbered.go
internal/bgp/frr/config.go
internal/bgp/frr/frr.go
internal/bgp/frr/frr_test.go
internal/bgp/frr/templates/neighboripfamily.tmpl
internal/bgp/frr/templates/neighborsession.tmpl
internal/bgp/frr/testdata/TestUnnumberedSession.golden

>
> /kind bug
/kind feature
> /kind design
> /kind flake
```release-note
Support Unnumbered BGP for frr backend
```

Support Unnumbered BGP for frr backend

---

ADOPTERS.md

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```

Add an official adopters list

---

ADOPTERS.md

>
> /kind bug
> /kind design
> /kind flake
```release-note
NONE
```

Adds SUSE as MetalLB adopter

---

ADOPTERS.md

Added Nokia EDA adopter

---

ADOPTERS.md

Add 1&1 Mail & Media to ADOPTERS.md
```release-note
NONE
```

Add 1&1 Mail & Media to adopters

---

ADOPTERS.md

>
> /kind bug
> /kind design
> /kind flake
```release-note
NONE
```

Add Clastix as adopter

---

go.mod

/kind cleanup
> /kind design
> /kind flake
```release-note
NONE
```

Fix go version specification and golang toolchain version
